// ignore_for_file: type=lint, type=warning, unused_field, unused_element, non_constant_identifier_names
// Generated by ffigen. Do not edit manually.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for OpenH264 (Cisco's software H.264 encoder/decoder).
/// Generated via: dart run ffigen --config tool/ffigen_openh264.yaml
///
class OpenH264Bindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OpenH264Bindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OpenH264Bindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// In a GOP, multiple of the key frame number, derived from the number of
  /// layers(index or array below)
  late final ffi.Pointer<ffi.Char> _kiKeyNumMultiple = _lookup<ffi.Char>(
    'kiKeyNumMultiple',
  );

  ffi.Pointer<ffi.Char> get kiKeyNumMultiple => _kiKeyNumMultiple;

  /// Create encoder
  int WelsCreateSVCEncoder(ffi.Pointer<ffi.Pointer<ISVCEncoder>> ppEncoder) {
    return _WelsCreateSVCEncoder(ppEncoder);
  }

  late final _WelsCreateSVCEncoderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Pointer<ISVCEncoder>>)
        >
      >('WelsCreateSVCEncoder');
  late final _WelsCreateSVCEncoder =
      _WelsCreateSVCEncoderPtr.asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ISVCEncoder>>)
      >();

  /// Destroy encoder
  void WelsDestroySVCEncoder(ffi.Pointer<ISVCEncoder> pEncoder) {
    return _WelsDestroySVCEncoder(pEncoder);
  }

  late final _WelsDestroySVCEncoderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ISVCEncoder>)>>(
        'WelsDestroySVCEncoder',
      );
  late final _WelsDestroySVCEncoder =
      _WelsDestroySVCEncoderPtr.asFunction<
        void Function(ffi.Pointer<ISVCEncoder>)
      >();

  /// Get the capability of decoder
  int WelsGetDecoderCapability(ffi.Pointer<SDecoderCapability> pDecCapability) {
    return _WelsGetDecoderCapability(pDecCapability);
  }

  late final _WelsGetDecoderCapabilityPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<SDecoderCapability>)>
      >('WelsGetDecoderCapability');
  late final _WelsGetDecoderCapability =
      _WelsGetDecoderCapabilityPtr.asFunction<
        int Function(ffi.Pointer<SDecoderCapability>)
      >();

  /// Create decoder
  int WelsCreateDecoder(ffi.Pointer<ffi.Pointer<ISVCDecoder>> ppDecoder) {
    return _WelsCreateDecoder(ppDecoder);
  }

  late final _WelsCreateDecoderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Pointer<ffi.Pointer<ISVCDecoder>>)
        >
      >('WelsCreateDecoder');
  late final _WelsCreateDecoder =
      _WelsCreateDecoderPtr.asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ISVCDecoder>>)
      >();

  /// Destroy decoder
  void WelsDestroyDecoder(ffi.Pointer<ISVCDecoder> pDecoder) {
    return _WelsDestroyDecoder(pDecoder);
  }

  late final _WelsDestroyDecoderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ISVCDecoder>)>>(
        'WelsDestroyDecoder',
      );
  late final _WelsDestroyDecoder =
      _WelsDestroyDecoderPtr.asFunction<
        void Function(ffi.Pointer<ISVCDecoder>)
      >();

  /// Get codec version Note, old versions of Mingw (GCC < 4.7) are buggy and
  /// use an incorrect/different ABI for calling this function, making it
  /// incompatible with MSVC builds.
  OpenH264Version WelsGetCodecVersion() {
    return _WelsGetCodecVersion();
  }

  late final _WelsGetCodecVersionPtr =
      _lookup<ffi.NativeFunction<OpenH264Version Function()>>(
        'WelsGetCodecVersion',
      );
  late final _WelsGetCodecVersion =
      _WelsGetCodecVersionPtr.asFunction<OpenH264Version Function()>();

  /// Get codec version
  void WelsGetCodecVersionEx(ffi.Pointer<OpenH264Version> pVersion) {
    return _WelsGetCodecVersionEx(pVersion);
  }

  late final _WelsGetCodecVersionExPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<OpenH264Version>)>
      >('WelsGetCodecVersionEx');
  late final _WelsGetCodecVersionEx =
      _WelsGetCodecVersionExPtr.asFunction<
        void Function(ffi.Pointer<OpenH264Version>)
      >();

  late final ffi.Pointer<OpenH264Version> _g_stCodecVersion =
      _lookup<OpenH264Version>('g_stCodecVersion');

  OpenH264Version get g_stCodecVersion => _g_stCodecVersion.ref;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _g_strCodecVer =
      _lookup<ffi.Pointer<ffi.Char>>('g_strCodecVer');

  ffi.Pointer<ffi.Char> get g_strCodecVer => _g_strCodecVer.value;
}

/// Enumerate the type of video format
enum EVideoFormatType {
  /// rgb color formats
  videoFormatRGB(1),
  videoFormatRGBA(2),
  videoFormatRGB555(3),
  videoFormatRGB565(4),
  videoFormatBGR(5),
  videoFormatBGRA(6),
  videoFormatABGR(7),
  videoFormatARGB(8),

  /// yuv color formats
  videoFormatYUY2(20),
  videoFormatYVYU(21),
  videoFormatUYVY(22),

  /// the same as IYUV
  videoFormatI420(23),
  videoFormatYV12(24),

  /// only used in SVC decoder testbed
  videoFormatInternal(25),

  /// new format for output by DXVA decoding
  videoFormatNV12(26),
  videoFormatVFlip(-2147483648);

  final int value;
  const EVideoFormatType(this.value);

  static EVideoFormatType fromValue(int value) => switch (value) {
    1 => videoFormatRGB,
    2 => videoFormatRGBA,
    3 => videoFormatRGB555,
    4 => videoFormatRGB565,
    5 => videoFormatBGR,
    6 => videoFormatBGRA,
    7 => videoFormatABGR,
    8 => videoFormatARGB,
    20 => videoFormatYUY2,
    21 => videoFormatYVYU,
    22 => videoFormatUYVY,
    23 => videoFormatI420,
    24 => videoFormatYV12,
    25 => videoFormatInternal,
    26 => videoFormatNV12,
    -2147483648 => videoFormatVFlip,
    _ => throw ArgumentError('Unknown value for EVideoFormatType: $value'),
  };
}

/// Enumerate video frame type
enum EVideoFrameType {
  /// encoder not ready or parameters are invalidate
  videoFrameTypeInvalid(0),

  /// IDR frame in H.264
  videoFrameTypeIDR(1),

  /// I frame type
  videoFrameTypeI(2),

  /// P frame type
  videoFrameTypeP(3),

  /// skip the frame based encoder kernel
  videoFrameTypeSkip(4),

  /// a frame where I and P slices are mixing, not supported yet
  videoFrameTypeIPMixed(5);

  final int value;
  const EVideoFrameType(this.value);

  static EVideoFrameType fromValue(int value) => switch (value) {
    0 => videoFrameTypeInvalid,
    1 => videoFrameTypeIDR,
    2 => videoFrameTypeI,
    3 => videoFrameTypeP,
    4 => videoFrameTypeSkip,
    5 => videoFrameTypeIPMixed,
    _ => throw ArgumentError('Unknown value for EVideoFrameType: $value'),
  };
}

/// Enumerate return type
enum CM_RETURN {
  /// successful
  cmResultSuccess(0),

  /// parameters are invalid
  cmInitParaError(1),
  cmUnknownReason(2),

  /// malloc a memory error
  cmMallocMemeError(3),

  /// initial action is expected
  cmInitExpected(4),
  cmUnsupportedData(5);

  final int value;
  const CM_RETURN(this.value);

  static CM_RETURN fromValue(int value) => switch (value) {
    0 => cmResultSuccess,
    1 => cmInitParaError,
    2 => cmUnknownReason,
    3 => cmMallocMemeError,
    4 => cmInitExpected,
    5 => cmUnsupportedData,
    _ => throw ArgumentError('Unknown value for CM_RETURN: $value'),
  };
}

/// Enumulate the nal unit type
enum ENalUnitType {
  NAL_UNKNOWN(0),
  NAL_SLICE(1),
  NAL_SLICE_DPA(2),
  NAL_SLICE_DPB(3),
  NAL_SLICE_DPC(4),

  /// ref_idc != 0
  NAL_SLICE_IDR(5),

  /// ref_idc == 0
  NAL_SEI(6),
  NAL_SPS(7),
  NAL_PPS(8);

  final int value;
  const ENalUnitType(this.value);

  static ENalUnitType fromValue(int value) => switch (value) {
    0 => NAL_UNKNOWN,
    1 => NAL_SLICE,
    2 => NAL_SLICE_DPA,
    3 => NAL_SLICE_DPB,
    4 => NAL_SLICE_DPC,
    5 => NAL_SLICE_IDR,
    6 => NAL_SEI,
    7 => NAL_SPS,
    8 => NAL_PPS,
    _ => throw ArgumentError('Unknown value for ENalUnitType: $value'),
  };
}

/// NRI: eNalRefIdc
enum ENalPriority {
  NAL_PRIORITY_DISPOSABLE(0),
  NAL_PRIORITY_LOW(1),
  NAL_PRIORITY_HIGH(2),
  NAL_PRIORITY_HIGHEST(3);

  final int value;
  const ENalPriority(this.value);

  static ENalPriority fromValue(int value) => switch (value) {
    0 => NAL_PRIORITY_DISPOSABLE,
    1 => NAL_PRIORITY_LOW,
    2 => NAL_PRIORITY_HIGH,
    3 => NAL_PRIORITY_HIGHEST,
    _ => throw ArgumentError('Unknown value for ENalPriority: $value'),
  };
}

/// Error Tools definition
typedef ERR_TOOL = ffi.UnsignedShort;
typedef DartERR_TOOL = int;

/// Information of coded Slice(=NAL)(s)
final class SliceInformation extends ffi.Struct {
  /// base buffer of coded slice(s)
  external ffi.Pointer<ffi.UnsignedChar> pBufferOfSlices;

  /// number of coded slices
  @ffi.Int()
  external int iCodedSliceCount;

  /// array of slices length accordingly by number of slice
  external ffi.Pointer<ffi.UnsignedInt> pLengthOfSlices;

  /// FEC type[0, 50%FEC, 100%FEC]
  @ffi.Int()
  external int iFecType;

  /// index of slice in frame [FMO: 0,..,uiSliceCount-1; No FMO: 0]
  @ffi.UnsignedChar()
  external int uiSliceIdx;

  /// count number of slice in frame [FMO: 2-8; No FMO: 1]
  @ffi.UnsignedChar()
  external int uiSliceCount;

  /// index of frame[-1, .., idr_interval-1]
  @ffi.Char()
  external int iFrameIndex;

  /// NRI, priority level of slice(NAL)
  @ffi.UnsignedChar()
  external int uiNalRefIdc;

  /// NAL type
  @ffi.UnsignedChar()
  external int uiNalType;

  /// whether final NAL is involved in buffer of coded slices, flag used in
  /// Pause feature in T27
  @ffi.UnsignedChar()
  external int uiContainingFinalNal;
}

/// Information of coded Slice(=NAL)(s)
typedef SliceInfo = SliceInformation;
typedef PSliceInfo = ffi.Pointer<SliceInformation>;

/// thresholds of the initial, maximal and minimal rate
final class SRateThresholds extends ffi.Struct {
  /// frame width
  @ffi.Int()
  external int iWidth;

  /// frame height
  @ffi.Int()
  external int iHeight;

  /// threshold of initial rate
  @ffi.Int()
  external int iThresholdOfInitRate;

  /// threshold of maximal rate
  @ffi.Int()
  external int iThresholdOfMaxRate;

  /// threshold of minimal rate
  @ffi.Int()
  external int iThresholdOfMinRate;

  /// min frame rate min
  @ffi.Int()
  external int iMinThresholdFrameRate;

  /// skip to frame rate min
  @ffi.Int()
  external int iSkipFrameRate;

  /// how many frames to skip
  @ffi.Int()
  external int iSkipFrameStep;
}

/// thresholds of the initial, maximal and minimal rate
typedef PRateThresholds = ffi.Pointer<SRateThresholds>;

/// Structure for decoder memery
final class TagSysMemBuffer extends ffi.Struct {
  /// width of decoded pic for display
  @ffi.Int()
  external int iWidth;

  /// height of decoded pic for display
  @ffi.Int()
  external int iHeight;

  /// type is "EVideoFormatType"
  @ffi.Int()
  external int iFormat;

  /// stride of 2 component
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> iStride;
}

/// Structure for decoder memery
typedef SSysMEMBuffer = TagSysMemBuffer;

final class UnnamedUnion1 extends ffi.Union {
  /// memory info for one picture
  external SSysMEMBuffer sSystemBuffer;
}

/// Buffer info
final class TagBufferInfo extends ffi.Struct {
  /// 0: one frame data is not ready; 1: one frame data is ready
  @ffi.Int()
  external int iBufferStatus;

  /// input BS timestamp
  @ffi.UnsignedLongLong()
  external int uiInBsTimeStamp;

  /// output YUV timestamp, when bufferstatus is 1
  @ffi.UnsignedLongLong()
  external int uiOutYuvTimeStamp;

  /// output buffer info
  external UnnamedUnion1 UsrData;

  /// point to picture YUV data
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Pointer<ffi.UnsignedChar>> pDst;
}

/// Buffer info
typedef SBufferInfo = TagBufferInfo;

/// Struct of OpenH264 version
final class _tagVersion extends ffi.Struct {
  /// The major version number
  @ffi.UnsignedInt()
  external int uMajor;

  /// The minor version number
  @ffi.UnsignedInt()
  external int uMinor;

  /// The revision number
  @ffi.UnsignedInt()
  external int uRevision;

  /// The reserved number, it should be 0.
  @ffi.UnsignedInt()
  external int uReserved;
}

/// Struct of OpenH264 version
typedef OpenH264Version = _tagVersion;

/// Decoding status
enum DECODING_STATE {
  /// bit stream error-free
  dsErrorFree(0),

  /// need more throughput to generate a frame output,
  dsFramePending(1),

  /// layer lost at reference frame with temporal id 0
  dsRefLost(2),

  /// error bitstreams(maybe broken internal frame) the decoder cared
  dsBitstreamError(4),

  /// dependented layer is ever lost
  dsDepLayerLost(8),

  /// no parameter set NALs involved
  dsNoParamSets(16),

  /// current data error concealed specified
  dsDataErrorConcealed(32),

  /// ref picure list contains null ptrs within uiRefCount range
  dsRefListNullPtrs(64),

  /// invalid argument specified
  dsInvalidArgument(4096),

  /// initializing operation is expected
  dsInitialOptExpected(8192),

  /// out of memory due to new request
  dsOutOfMemory(16384),

  /// actual picture size exceeds size of dst pBuffer feed in decoder, so need
  /// expand its size
  dsDstBufNeedExpan(32768);

  final int value;
  const DECODING_STATE(this.value);

  static DECODING_STATE fromValue(int value) => switch (value) {
    0 => dsErrorFree,
    1 => dsFramePending,
    2 => dsRefLost,
    4 => dsBitstreamError,
    8 => dsDepLayerLost,
    16 => dsNoParamSets,
    32 => dsDataErrorConcealed,
    64 => dsRefListNullPtrs,
    4096 => dsInvalidArgument,
    8192 => dsInitialOptExpected,
    16384 => dsOutOfMemory,
    32768 => dsDstBufNeedExpan,
    _ => throw ArgumentError('Unknown value for DECODING_STATE: $value'),
  };
}

/// Option types introduced in SVC encoder application
enum ENCODER_OPTION {
  ENCODER_OPTION_DATAFORMAT(0),

  /// IDR period,0/-1 means no Intra period (only the first frame); lager than 0
  /// means the desired IDR period, must be multiple of (2^temporal_layer)
  ENCODER_OPTION_IDR_INTERVAL(1),

  /// structure of Base Param
  ENCODER_OPTION_SVC_ENCODE_PARAM_BASE(2),

  /// structure of Extension Param
  ENCODER_OPTION_SVC_ENCODE_PARAM_EXT(3),

  /// maximal input frame rate, current supported range: MAX_FRAME_RATE =
  /// 30,MIN_FRAME_RATE = 1
  ENCODER_OPTION_FRAME_RATE(4),
  ENCODER_OPTION_BITRATE(5),
  ENCODER_OPTION_MAX_BITRATE(6),
  ENCODER_OPTION_INTER_SPATIAL_PRED(7),
  ENCODER_OPTION_RC_MODE(8),
  ENCODER_OPTION_RC_FRAME_SKIP(9),

  /// 0:disable padding;1:padding
  ENCODER_PADDING_PADDING(10),

  /// assgin the profile for each layer
  ENCODER_OPTION_PROFILE(11),

  /// assgin the level for each layer
  ENCODER_OPTION_LEVEL(12),

  /// the number of refererence frame
  ENCODER_OPTION_NUMBER_REF(13),

  /// the delivery info which is a feedback from app level
  ENCODER_OPTION_DELIVERY_STATUS(14),
  ENCODER_LTR_RECOVERY_REQUEST(15),
  ENCODER_LTR_MARKING_FEEDBACK(16),
  ENCODER_LTR_MARKING_PERIOD(17),

  /// 0:disable LTR;larger than 0 enable LTR; LTR number is fixed to be 2 in
  /// current encoder
  ENCODER_OPTION_LTR(18),
  ENCODER_OPTION_COMPLEXITY(19),

  /// enable SSEI: true--enable ssei; false--disable ssei
  ENCODER_OPTION_ENABLE_SSEI(20),

  /// enable prefix: true--enable prefix; false--disable prefix
  ENCODER_OPTION_ENABLE_PREFIX_NAL_ADDING(21),

  /// different stategy in adjust ID in SPS/PPS: 0- constant ID, 1-additional
  /// ID, 6-mapping and additional
  ENCODER_OPTION_SPS_PPS_ID_STRATEGY(22),
  ENCODER_OPTION_CURRENT_PATH(23),

  /// dump layer reconstruct frame to a specified file
  ENCODER_OPTION_DUMP_FILE(24),

  /// trace info based on the trace level
  ENCODER_OPTION_TRACE_LEVEL(25),

  /// a void (*)(void* context, int level, const char* message) function which
  /// receives log messages
  ENCODER_OPTION_TRACE_CALLBACK(26),

  /// context info of trace callback
  ENCODER_OPTION_TRACE_CALLBACK_CONTEXT(27),

  /// read only
  ENCODER_OPTION_GET_STATISTICS(28),

  /// log interval in millisecond
  ENCODER_OPTION_STATISTICS_LOG_INTERVAL(29),

  /// advanced algorithmetic settings
  ENCODER_OPTION_IS_LOSSLESS_LINK(30),

  /// bit vary percentage
  ENCODER_OPTION_BITS_VARY_PERCENTAGE(31);

  final int value;
  const ENCODER_OPTION(this.value);

  static ENCODER_OPTION fromValue(int value) => switch (value) {
    0 => ENCODER_OPTION_DATAFORMAT,
    1 => ENCODER_OPTION_IDR_INTERVAL,
    2 => ENCODER_OPTION_SVC_ENCODE_PARAM_BASE,
    3 => ENCODER_OPTION_SVC_ENCODE_PARAM_EXT,
    4 => ENCODER_OPTION_FRAME_RATE,
    5 => ENCODER_OPTION_BITRATE,
    6 => ENCODER_OPTION_MAX_BITRATE,
    7 => ENCODER_OPTION_INTER_SPATIAL_PRED,
    8 => ENCODER_OPTION_RC_MODE,
    9 => ENCODER_OPTION_RC_FRAME_SKIP,
    10 => ENCODER_PADDING_PADDING,
    11 => ENCODER_OPTION_PROFILE,
    12 => ENCODER_OPTION_LEVEL,
    13 => ENCODER_OPTION_NUMBER_REF,
    14 => ENCODER_OPTION_DELIVERY_STATUS,
    15 => ENCODER_LTR_RECOVERY_REQUEST,
    16 => ENCODER_LTR_MARKING_FEEDBACK,
    17 => ENCODER_LTR_MARKING_PERIOD,
    18 => ENCODER_OPTION_LTR,
    19 => ENCODER_OPTION_COMPLEXITY,
    20 => ENCODER_OPTION_ENABLE_SSEI,
    21 => ENCODER_OPTION_ENABLE_PREFIX_NAL_ADDING,
    22 => ENCODER_OPTION_SPS_PPS_ID_STRATEGY,
    23 => ENCODER_OPTION_CURRENT_PATH,
    24 => ENCODER_OPTION_DUMP_FILE,
    25 => ENCODER_OPTION_TRACE_LEVEL,
    26 => ENCODER_OPTION_TRACE_CALLBACK,
    27 => ENCODER_OPTION_TRACE_CALLBACK_CONTEXT,
    28 => ENCODER_OPTION_GET_STATISTICS,
    29 => ENCODER_OPTION_STATISTICS_LOG_INTERVAL,
    30 => ENCODER_OPTION_IS_LOSSLESS_LINK,
    31 => ENCODER_OPTION_BITS_VARY_PERCENTAGE,
    _ => throw ArgumentError('Unknown value for ENCODER_OPTION: $value'),
  };
}

/// Option types introduced in decoder application
enum DECODER_OPTION {
  /// end of stream flag
  DECODER_OPTION_END_OF_STREAM(1),

  /// feedback whether or not have VCL NAL in current AU for application layer
  DECODER_OPTION_VCL_NAL(2),

  /// feedback temporal id for application layer
  DECODER_OPTION_TEMPORAL_ID(3),

  /// feedback current decoded frame number
  DECODER_OPTION_FRAME_NUM(4),

  /// feedback current frame belong to which IDR period
  DECODER_OPTION_IDR_PIC_ID(5),

  /// feedback wether current frame mark a LTR
  DECODER_OPTION_LTR_MARKING_FLAG(6),

  /// feedback frame num marked by current Frame
  DECODER_OPTION_LTR_MARKED_FRAME_NUM(7),

  /// indicate decoder error concealment method
  DECODER_OPTION_ERROR_CON_IDC(8),
  DECODER_OPTION_TRACE_LEVEL(9),

  /// a void (*)(void* context, int level, const char* message) function which
  /// receives log messages
  DECODER_OPTION_TRACE_CALLBACK(10),

  /// context info of trace callbac
  DECODER_OPTION_TRACE_CALLBACK_CONTEXT(11),

  /// feedback decoder statistics
  DECODER_OPTION_GET_STATISTICS(12),

  /// feedback decoder Sample Aspect Ratio info in Vui
  DECODER_OPTION_GET_SAR_INFO(13),

  /// get current AU profile info, only is used in GetOption
  DECODER_OPTION_PROFILE(14),

  /// get current AU level info,only is used in GetOption
  DECODER_OPTION_LEVEL(15),

  /// set log output interval
  DECODER_OPTION_STATISTICS_LOG_INTERVAL(16),

  /// feedback current frame is ref pic or not
  DECODER_OPTION_IS_REF_PIC(17),

  /// number of frames remaining in decoder buffer when pictures are required to
  /// re-ordered into display-order.
  DECODER_OPTION_NUM_OF_FRAMES_REMAINING_IN_BUFFER(18),

  /// number of decoding threads. The maximum thread count is equal or less than
  /// lesser of (cpu core counts and 16).
  DECODER_OPTION_NUM_OF_THREADS(19);

  final int value;
  const DECODER_OPTION(this.value);

  static DECODER_OPTION fromValue(int value) => switch (value) {
    1 => DECODER_OPTION_END_OF_STREAM,
    2 => DECODER_OPTION_VCL_NAL,
    3 => DECODER_OPTION_TEMPORAL_ID,
    4 => DECODER_OPTION_FRAME_NUM,
    5 => DECODER_OPTION_IDR_PIC_ID,
    6 => DECODER_OPTION_LTR_MARKING_FLAG,
    7 => DECODER_OPTION_LTR_MARKED_FRAME_NUM,
    8 => DECODER_OPTION_ERROR_CON_IDC,
    9 => DECODER_OPTION_TRACE_LEVEL,
    10 => DECODER_OPTION_TRACE_CALLBACK,
    11 => DECODER_OPTION_TRACE_CALLBACK_CONTEXT,
    12 => DECODER_OPTION_GET_STATISTICS,
    13 => DECODER_OPTION_GET_SAR_INFO,
    14 => DECODER_OPTION_PROFILE,
    15 => DECODER_OPTION_LEVEL,
    16 => DECODER_OPTION_STATISTICS_LOG_INTERVAL,
    17 => DECODER_OPTION_IS_REF_PIC,
    18 => DECODER_OPTION_NUM_OF_FRAMES_REMAINING_IN_BUFFER,
    19 => DECODER_OPTION_NUM_OF_THREADS,
    _ => throw ArgumentError('Unknown value for DECODER_OPTION: $value'),
  };
}

/// Enumerate the type of error concealment methods
enum ERROR_CON_IDC {
  ERROR_CON_DISABLE(0),
  ERROR_CON_FRAME_COPY(1),
  ERROR_CON_SLICE_COPY(2),
  ERROR_CON_FRAME_COPY_CROSS_IDR(3),
  ERROR_CON_SLICE_COPY_CROSS_IDR(4),
  ERROR_CON_SLICE_COPY_CROSS_IDR_FREEZE_RES_CHANGE(5),
  ERROR_CON_SLICE_MV_COPY_CROSS_IDR(6),
  ERROR_CON_SLICE_MV_COPY_CROSS_IDR_FREEZE_RES_CHANGE(7);

  final int value;
  const ERROR_CON_IDC(this.value);

  static ERROR_CON_IDC fromValue(int value) => switch (value) {
    0 => ERROR_CON_DISABLE,
    1 => ERROR_CON_FRAME_COPY,
    2 => ERROR_CON_SLICE_COPY,
    3 => ERROR_CON_FRAME_COPY_CROSS_IDR,
    4 => ERROR_CON_SLICE_COPY_CROSS_IDR,
    5 => ERROR_CON_SLICE_COPY_CROSS_IDR_FREEZE_RES_CHANGE,
    6 => ERROR_CON_SLICE_MV_COPY_CROSS_IDR,
    7 => ERROR_CON_SLICE_MV_COPY_CROSS_IDR_FREEZE_RES_CHANGE,
    _ => throw ArgumentError('Unknown value for ERROR_CON_IDC: $value'),
  };
}

/// Spatial layer num
enum LAYER_NUM {
  SPATIAL_LAYER_0(0),
  SPATIAL_LAYER_1(1),
  SPATIAL_LAYER_2(2),
  SPATIAL_LAYER_3(3),
  SPATIAL_LAYER_ALL(4);

  final int value;
  const LAYER_NUM(this.value);

  static LAYER_NUM fromValue(int value) => switch (value) {
    0 => SPATIAL_LAYER_0,
    1 => SPATIAL_LAYER_1,
    2 => SPATIAL_LAYER_2,
    3 => SPATIAL_LAYER_3,
    4 => SPATIAL_LAYER_ALL,
    _ => throw ArgumentError('Unknown value for LAYER_NUM: $value'),
  };
}

/// Enumerate the type of video bitstream which is provided to decoder
enum VIDEO_BITSTREAM_TYPE {
  VIDEO_BITSTREAM_AVC(0),
  VIDEO_BITSTREAM_SVC(1);

  static const VIDEO_BITSTREAM_DEFAULT = VIDEO_BITSTREAM_SVC;

  final int value;
  const VIDEO_BITSTREAM_TYPE(this.value);

  static VIDEO_BITSTREAM_TYPE fromValue(int value) => switch (value) {
    0 => VIDEO_BITSTREAM_AVC,
    1 => VIDEO_BITSTREAM_SVC,
    _ => throw ArgumentError('Unknown value for VIDEO_BITSTREAM_TYPE: $value'),
  };

  @override
  String toString() {
    if (this == VIDEO_BITSTREAM_SVC)
      return "VIDEO_BITSTREAM_TYPE.VIDEO_BITSTREAM_SVC, VIDEO_BITSTREAM_TYPE.VIDEO_BITSTREAM_DEFAULT";
    return super.toString();
  }
}

/// Structure for LTR recover request
final class SLTRRecoverRequest extends ffi.Struct {
  /// IDR request or LTR recovery request
  @ffi.UnsignedInt()
  external int uiFeedbackType;

  /// distinguish request from different IDR
  @ffi.UnsignedInt()
  external int uiIDRPicId;

  @ffi.Int()
  external int iLastCorrectFrameNum;

  /// specify current decoder frame_num.
  @ffi.Int()
  external int iCurrentFrameNum;

  /// specify the layer for recovery request
  @ffi.Int()
  external int iLayerId;
}

/// Structure for LTR marking feedback
final class SLTRMarkingFeedback extends ffi.Struct {
  /// mark failed or successful
  @ffi.UnsignedInt()
  external int uiFeedbackType;

  /// distinguish request from different IDR
  @ffi.UnsignedInt()
  external int uiIDRPicId;

  /// specify current decoder frame_num
  @ffi.Int()
  external int iLTRFrameNum;

  /// specify the layer for LTR marking feedback
  @ffi.Int()
  external int iLayerId;
}

/// Structure for LTR configuration
final class SLTRConfig extends ffi.Struct {
  /// 1: on, 0: off
  @ffi.Bool()
  external bool bEnableLongTermReference;

  /// TODO: not supported to set it arbitrary yet
  @ffi.Int()
  external int iLTRRefNum;
}

/// Enumerate the type of rate control mode
enum RC_MODES {
  /// quality mode
  RC_QUALITY_MODE(0),

  /// bitrate mode
  RC_BITRATE_MODE(1),

  /// no bitrate control,only using buffer status,adjust the video quality
  RC_BUFFERBASED_MODE(2),

  /// rate control based timestamp
  RC_TIMESTAMP_MODE(3),

  /// this is in-building RC MODE, WILL BE DELETED after algorithm tuning!
  RC_BITRATE_MODE_POST_SKIP(4),

  /// rate control off mode
  RC_OFF_MODE(-1);

  final int value;
  const RC_MODES(this.value);

  static RC_MODES fromValue(int value) => switch (value) {
    0 => RC_QUALITY_MODE,
    1 => RC_BITRATE_MODE,
    2 => RC_BUFFERBASED_MODE,
    3 => RC_TIMESTAMP_MODE,
    4 => RC_BITRATE_MODE_POST_SKIP,
    -1 => RC_OFF_MODE,
    _ => throw ArgumentError('Unknown value for RC_MODES: $value'),
  };
}

/// Enumerate the type of profile id
enum EProfileIdc {
  PRO_UNKNOWN(0),
  PRO_BASELINE(66),
  PRO_MAIN(77),
  PRO_EXTENDED(88),
  PRO_HIGH(100),
  PRO_HIGH10(110),
  PRO_HIGH422(122),
  PRO_HIGH444(144),
  PRO_CAVLC444(244),
  PRO_SCALABLE_BASELINE(83),
  PRO_SCALABLE_HIGH(86);

  final int value;
  const EProfileIdc(this.value);

  static EProfileIdc fromValue(int value) => switch (value) {
    0 => PRO_UNKNOWN,
    66 => PRO_BASELINE,
    77 => PRO_MAIN,
    88 => PRO_EXTENDED,
    100 => PRO_HIGH,
    110 => PRO_HIGH10,
    122 => PRO_HIGH422,
    144 => PRO_HIGH444,
    244 => PRO_CAVLC444,
    83 => PRO_SCALABLE_BASELINE,
    86 => PRO_SCALABLE_HIGH,
    _ => throw ArgumentError('Unknown value for EProfileIdc: $value'),
  };
}

/// Enumerate the type of level id
enum ELevelIdc {
  LEVEL_UNKNOWN(0),
  LEVEL_1_0(10),
  LEVEL_1_B(9),
  LEVEL_1_1(11),
  LEVEL_1_2(12),
  LEVEL_1_3(13),
  LEVEL_2_0(20),
  LEVEL_2_1(21),
  LEVEL_2_2(22),
  LEVEL_3_0(30),
  LEVEL_3_1(31),
  LEVEL_3_2(32),
  LEVEL_4_0(40),
  LEVEL_4_1(41),
  LEVEL_4_2(42),
  LEVEL_5_0(50),
  LEVEL_5_1(51),
  LEVEL_5_2(52);

  final int value;
  const ELevelIdc(this.value);

  static ELevelIdc fromValue(int value) => switch (value) {
    0 => LEVEL_UNKNOWN,
    10 => LEVEL_1_0,
    9 => LEVEL_1_B,
    11 => LEVEL_1_1,
    12 => LEVEL_1_2,
    13 => LEVEL_1_3,
    20 => LEVEL_2_0,
    21 => LEVEL_2_1,
    22 => LEVEL_2_2,
    30 => LEVEL_3_0,
    31 => LEVEL_3_1,
    32 => LEVEL_3_2,
    40 => LEVEL_4_0,
    41 => LEVEL_4_1,
    42 => LEVEL_4_2,
    50 => LEVEL_5_0,
    51 => LEVEL_5_1,
    52 => LEVEL_5_2,
    _ => throw ArgumentError('Unknown value for ELevelIdc: $value'),
  };
}

/// Enumerate the type of slice mode
enum SliceModeEnum {
  /// | SliceNum==1
  SM_SINGLE_SLICE(0),

  /// | according to SliceNum | enabled dynamic slicing for multi-thread
  SM_FIXEDSLCNUM_SLICE(1),

  /// | according to SlicesAssign | need input of MB numbers each slice. In
  /// addition, if other constraint in SSliceArgument is presented, need to
  /// follow the constraints. Typically if MB num and slice size are both
  /// constrained, re-encoding may be involved.
  SM_RASTER_SLICE(2),

  /// | according to SliceSize | slicing according to size, the slicing will be
  /// dynamic(have no idea about slice_nums until encoding current frame)
  SM_SIZELIMITED_SLICE(3),
  SM_RESERVED(4);

  final int value;
  const SliceModeEnum(this.value);

  static SliceModeEnum fromValue(int value) => switch (value) {
    0 => SM_SINGLE_SLICE,
    1 => SM_FIXEDSLCNUM_SLICE,
    2 => SM_RASTER_SLICE,
    3 => SM_SIZELIMITED_SLICE,
    4 => SM_RESERVED,
    _ => throw ArgumentError('Unknown value for SliceModeEnum: $value'),
  };
}

/// Structure for slice argument
final class SSliceArgument extends ffi.Struct {
  /// by default, uiSliceMode will be SM_SINGLE_SLICE
  @ffi.UnsignedInt()
  external int uiSliceModeAsInt;

  SliceModeEnum get uiSliceMode => SliceModeEnum.fromValue(uiSliceModeAsInt);

  /// only used when uiSliceMode=1, when uiSliceNum=0 means auto design it with
  /// cpu core number
  @ffi.UnsignedInt()
  external int uiSliceNum;

  /// only used when uiSliceMode=2; when =0 means setting one MB row a slice
  @ffi.Array.multi([35])
  external ffi.Array<ffi.UnsignedInt> uiSliceMbNum;

  /// now only used when uiSliceMode=4
  @ffi.UnsignedInt()
  external int uiSliceSizeConstraint;
}

/// Enumerate the type of video format
enum EVideoFormatSPS {
  VF_COMPONENT(0),
  VF_PAL(1),
  VF_NTSC(2),
  VF_SECAM(3),
  VF_MAC(4),
  VF_UNDEF(5),
  VF_NUM_ENUM(6);

  final int value;
  const EVideoFormatSPS(this.value);

  static EVideoFormatSPS fromValue(int value) => switch (value) {
    0 => VF_COMPONENT,
    1 => VF_PAL,
    2 => VF_NTSC,
    3 => VF_SECAM,
    4 => VF_MAC,
    5 => VF_UNDEF,
    6 => VF_NUM_ENUM,
    _ => throw ArgumentError('Unknown value for EVideoFormatSPS: $value'),
  };
}

/// Enumerate the type of color primaries
enum EColorPrimaries {
  CP_RESERVED0(0),
  CP_BT709(1),
  CP_UNDEF(2),
  CP_RESERVED3(3),
  CP_BT470M(4),
  CP_BT470BG(5),
  CP_SMPTE170M(6),
  CP_SMPTE240M(7),
  CP_FILM(8),
  CP_BT2020(9),
  CP_NUM_ENUM(10);

  final int value;
  const EColorPrimaries(this.value);

  static EColorPrimaries fromValue(int value) => switch (value) {
    0 => CP_RESERVED0,
    1 => CP_BT709,
    2 => CP_UNDEF,
    3 => CP_RESERVED3,
    4 => CP_BT470M,
    5 => CP_BT470BG,
    6 => CP_SMPTE170M,
    7 => CP_SMPTE240M,
    8 => CP_FILM,
    9 => CP_BT2020,
    10 => CP_NUM_ENUM,
    _ => throw ArgumentError('Unknown value for EColorPrimaries: $value'),
  };
}

/// Enumerate the type of transfer characteristics
enum ETransferCharacteristics {
  TRC_RESERVED0(0),
  TRC_BT709(1),
  TRC_UNDEF(2),
  TRC_RESERVED3(3),
  TRC_BT470M(4),
  TRC_BT470BG(5),
  TRC_SMPTE170M(6),
  TRC_SMPTE240M(7),
  TRC_LINEAR(8),
  TRC_LOG100(9),
  TRC_LOG316(10),
  TRC_IEC61966_2_4(11),
  TRC_BT1361E(12),
  TRC_IEC61966_2_1(13),
  TRC_BT2020_10(14),
  TRC_BT2020_12(15),
  TRC_NUM_ENUM(16);

  final int value;
  const ETransferCharacteristics(this.value);

  static ETransferCharacteristics fromValue(int value) => switch (value) {
    0 => TRC_RESERVED0,
    1 => TRC_BT709,
    2 => TRC_UNDEF,
    3 => TRC_RESERVED3,
    4 => TRC_BT470M,
    5 => TRC_BT470BG,
    6 => TRC_SMPTE170M,
    7 => TRC_SMPTE240M,
    8 => TRC_LINEAR,
    9 => TRC_LOG100,
    10 => TRC_LOG316,
    11 => TRC_IEC61966_2_4,
    12 => TRC_BT1361E,
    13 => TRC_IEC61966_2_1,
    14 => TRC_BT2020_10,
    15 => TRC_BT2020_12,
    16 => TRC_NUM_ENUM,
    _ => throw ArgumentError(
      'Unknown value for ETransferCharacteristics: $value',
    ),
  };
}

/// Enumerate the type of color matrix
enum EColorMatrix {
  CM_GBR(0),
  CM_BT709(1),
  CM_UNDEF(2),
  CM_RESERVED3(3),
  CM_FCC(4),
  CM_BT470BG(5),
  CM_SMPTE170M(6),
  CM_SMPTE240M(7),
  CM_YCGCO(8),
  CM_BT2020NC(9),
  CM_BT2020C(10),
  CM_NUM_ENUM(11);

  final int value;
  const EColorMatrix(this.value);

  static EColorMatrix fromValue(int value) => switch (value) {
    0 => CM_GBR,
    1 => CM_BT709,
    2 => CM_UNDEF,
    3 => CM_RESERVED3,
    4 => CM_FCC,
    5 => CM_BT470BG,
    6 => CM_SMPTE170M,
    7 => CM_SMPTE240M,
    8 => CM_YCGCO,
    9 => CM_BT2020NC,
    10 => CM_BT2020C,
    11 => CM_NUM_ENUM,
    _ => throw ArgumentError('Unknown value for EColorMatrix: $value'),
  };
}

/// Enumerate the type of sample aspect ratio
enum ESampleAspectRatio {
  ASP_UNSPECIFIED(0),
  ASP_1x1(1),
  ASP_12x11(2),
  ASP_10x11(3),
  ASP_16x11(4),
  ASP_40x33(5),
  ASP_24x11(6),
  ASP_20x11(7),
  ASP_32x11(8),
  ASP_80x33(9),
  ASP_18x11(10),
  ASP_15x11(11),
  ASP_64x33(12),
  ASP_160x99(13),
  ASP_EXT_SAR(255);

  final int value;
  const ESampleAspectRatio(this.value);

  static ESampleAspectRatio fromValue(int value) => switch (value) {
    0 => ASP_UNSPECIFIED,
    1 => ASP_1x1,
    2 => ASP_12x11,
    3 => ASP_10x11,
    4 => ASP_16x11,
    5 => ASP_40x33,
    6 => ASP_24x11,
    7 => ASP_20x11,
    8 => ASP_32x11,
    9 => ASP_80x33,
    10 => ASP_18x11,
    11 => ASP_15x11,
    12 => ASP_64x33,
    13 => ASP_160x99,
    255 => ASP_EXT_SAR,
    _ => throw ArgumentError('Unknown value for ESampleAspectRatio: $value'),
  };
}

/// Structure for spatial layer configuration
final class SSpatialLayerConfig extends ffi.Struct {
  /// width of picture in luminance samples of a layer
  @ffi.Int()
  external int iVideoWidth;

  /// height of picture in luminance samples of a layer
  @ffi.Int()
  external int iVideoHeight;

  /// frame rate specified for a layer
  @ffi.Float()
  external double fFrameRate;

  /// target bitrate for a spatial layer, in unit of bps
  @ffi.Int()
  external int iSpatialBitrate;

  /// maximum bitrate for a spatial layer, in unit of bps
  @ffi.Int()
  external int iMaxSpatialBitrate;

  /// value of profile IDC (PRO_UNKNOWN for auto-detection)
  @ffi.UnsignedInt()
  external int uiProfileIdcAsInt;

  EProfileIdc get uiProfileIdc => EProfileIdc.fromValue(uiProfileIdcAsInt);

  /// value of profile IDC (0 for auto-detection)
  @ffi.UnsignedInt()
  external int uiLevelIdcAsInt;

  ELevelIdc get uiLevelIdc => ELevelIdc.fromValue(uiLevelIdcAsInt);

  /// value of level IDC (0 for auto-detection)
  @ffi.Int()
  external int iDLayerQp;

  external SSliceArgument sSliceArgument;

  /// false => do not write any of the following information to the header
  @ffi.Bool()
  external bool bVideoSignalTypePresent;

  /// EVideoFormatSPS; 3 bits in header; 0-5 => component, kpal, ntsc, secam,
  /// mac, undef
  @ffi.UnsignedChar()
  external int uiVideoFormat;

  /// false => analog video data range [16, 235]; true => full data range
  /// [0,255]
  @ffi.Bool()
  external bool bFullRange;

  /// false => do not write any of the following three items to the header
  @ffi.Bool()
  external bool bColorDescriptionPresent;

  /// EColorPrimaries; 8 bits in header; 0 - 9 => ???, bt709, undef, ???,
  /// bt470m, bt470bg,
  @ffi.UnsignedChar()
  external int uiColorPrimaries;

  /// ETransferCharacteristics; 8 bits in header; 0 - 15 => ???, bt709, undef,
  /// ???, bt470m, bt470bg, smpte170m,
  @ffi.UnsignedChar()
  external int uiTransferCharacteristics;

  /// EColorMatrix; 8 bits in header (corresponds to FFmpeg "colorspace"); 0 -
  /// 10 => GBR, bt709,
  @ffi.UnsignedChar()
  external int uiColorMatrix;

  /// aspect ratio present in VUI
  @ffi.Bool()
  external bool bAspectRatioPresent;

  /// aspect ratio idc
  @ffi.UnsignedInt()
  external int eAspectRatioAsInt;

  ESampleAspectRatio get eAspectRatio =>
      ESampleAspectRatio.fromValue(eAspectRatioAsInt);

  /// use if aspect ratio idc == 255
  @ffi.UnsignedShort()
  external int sAspectRatioExtWidth;

  /// use if aspect ratio idc == 255
  @ffi.UnsignedShort()
  external int sAspectRatioExtHeight;
}

/// Encoder usage type
enum EUsageType {
  /// camera video for real-time communication
  CAMERA_VIDEO_REAL_TIME(0),

  /// screen content signal
  SCREEN_CONTENT_REAL_TIME(1),
  CAMERA_VIDEO_NON_REAL_TIME(2),
  SCREEN_CONTENT_NON_REAL_TIME(3),
  INPUT_CONTENT_TYPE_ALL(4);

  final int value;
  const EUsageType(this.value);

  static EUsageType fromValue(int value) => switch (value) {
    0 => CAMERA_VIDEO_REAL_TIME,
    1 => SCREEN_CONTENT_REAL_TIME,
    2 => CAMERA_VIDEO_NON_REAL_TIME,
    3 => SCREEN_CONTENT_NON_REAL_TIME,
    4 => INPUT_CONTENT_TYPE_ALL,
    _ => throw ArgumentError('Unknown value for EUsageType: $value'),
  };
}

/// Enumulate the complexity mode
enum ECOMPLEXITY_MODE {
  /// the lowest compleixty,the fastest speed,
  LOW_COMPLEXITY(0),

  /// medium complexity, medium speed,medium quality
  MEDIUM_COMPLEXITY(1),

  /// high complexity, lowest speed, high quality
  HIGH_COMPLEXITY(2);

  final int value;
  const ECOMPLEXITY_MODE(this.value);

  static ECOMPLEXITY_MODE fromValue(int value) => switch (value) {
    0 => LOW_COMPLEXITY,
    1 => MEDIUM_COMPLEXITY,
    2 => HIGH_COMPLEXITY,
    _ => throw ArgumentError('Unknown value for ECOMPLEXITY_MODE: $value'),
  };
}

/// Enumulate for the stategy of SPS/PPS strategy
enum EParameterSetStrategy {
  /// constant id in SPS/PPS
  CONSTANT_ID(0),

  /// SPS/PPS id increases at each IDR
  INCREASING_ID(1),

  /// using SPS in the existing list if possible
  SPS_LISTING(2),
  SPS_LISTING_AND_PPS_INCREASING(3),
  SPS_PPS_LISTING(6);

  final int value;
  const EParameterSetStrategy(this.value);

  static EParameterSetStrategy fromValue(int value) => switch (value) {
    0 => CONSTANT_ID,
    1 => INCREASING_ID,
    2 => SPS_LISTING,
    3 => SPS_LISTING_AND_PPS_INCREASING,
    6 => SPS_PPS_LISTING,
    _ => throw ArgumentError('Unknown value for EParameterSetStrategy: $value'),
  };
}

/// SVC Encoding Parameters
final class TagEncParamBase extends ffi.Struct {
  /// application type; please refer to the definition of EUsageType
  @ffi.UnsignedInt()
  external int iUsageTypeAsInt;

  EUsageType get iUsageType => EUsageType.fromValue(iUsageTypeAsInt);

  /// width of picture in luminance samples (the maximum of all layers if
  /// multiple spatial layers presents)
  @ffi.Int()
  external int iPicWidth;

  /// height of picture in luminance samples((the maximum of all layers if
  /// multiple spatial layers presents)
  @ffi.Int()
  external int iPicHeight;

  /// target bitrate desired, in unit of bps
  @ffi.Int()
  external int iTargetBitrate;

  /// rate control mode
  @ffi.Int()
  external int iRCModeAsInt;

  RC_MODES get iRCMode => RC_MODES.fromValue(iRCModeAsInt);

  /// maximal input frame rate
  @ffi.Float()
  external double fMaxFrameRate;
}

/// SVC Encoding Parameters
typedef SEncParamBase = TagEncParamBase;
typedef PEncParamBase = ffi.Pointer<TagEncParamBase>;

/// SVC Encoding Parameters extention
final class TagEncParamExt extends ffi.Struct {
  /// same as in TagEncParamBase
  @ffi.UnsignedInt()
  external int iUsageTypeAsInt;

  EUsageType get iUsageType => EUsageType.fromValue(iUsageTypeAsInt);

  /// same as in TagEncParamBase
  @ffi.Int()
  external int iPicWidth;

  /// same as in TagEncParamBase
  @ffi.Int()
  external int iPicHeight;

  /// same as in TagEncParamBase
  @ffi.Int()
  external int iTargetBitrate;

  /// same as in TagEncParamBase
  @ffi.Int()
  external int iRCModeAsInt;

  RC_MODES get iRCMode => RC_MODES.fromValue(iRCModeAsInt);

  /// same as in TagEncParamBase
  @ffi.Float()
  external double fMaxFrameRate;

  /// temporal layer number, max temporal layer = 4
  @ffi.Int()
  external int iTemporalLayerNum;

  /// spatial layer number,1<= iSpatialLayerNum <= MAX_SPATIAL_LAYER_NUM,
  /// MAX_SPATIAL_LAYER_NUM = 4
  @ffi.Int()
  external int iSpatialLayerNum;

  @ffi.Array.multi([4])
  external ffi.Array<SSpatialLayerConfig> sSpatialLayers;

  @ffi.UnsignedInt()
  external int iComplexityModeAsInt;

  ECOMPLEXITY_MODE get iComplexityMode =>
      ECOMPLEXITY_MODE.fromValue(iComplexityModeAsInt);

  /// period of Intra frame
  @ffi.UnsignedInt()
  external int uiIntraPeriod;

  /// number of reference frame used
  @ffi.Int()
  external int iNumRefFrame;

  /// different stategy in adjust ID in SPS/PPS: 0- constant ID, 1-additional
  /// ID, 6-mapping and additional
  @ffi.UnsignedInt()
  external int eSpsPpsIdStrategyAsInt;

  EParameterSetStrategy get eSpsPpsIdStrategy =>
      EParameterSetStrategy.fromValue(eSpsPpsIdStrategyAsInt);

  /// false:not use Prefix NAL; true: use Prefix NAL
  @ffi.Bool()
  external bool bPrefixNalAddingCtrl;

  /// false:not use SSEI; true: use SSEI -- TODO: planning to remove the
  /// interface of SSEI
  @ffi.Bool()
  external bool bEnableSSEI;

  /// (when encoding more than 1 spatial layer) false: use SVC syntax for higher
  /// layers; true: use Simulcast AVC
  @ffi.Bool()
  external bool bSimulcastAVC;

  /// 0:disable padding;1:padding
  @ffi.Int()
  external int iPaddingFlag;

  /// 0:CAVLC 1:CABAC.
  @ffi.Int()
  external int iEntropyCodingModeFlag;

  /// False: don't skip frame even if VBV buffer overflow.True: allow skipping
  /// frames to keep the bitrate within limits
  @ffi.Bool()
  external bool bEnableFrameSkip;

  /// the maximum bitrate, in unit of bps, set it to UNSPECIFIED_BIT_RATE if not
  /// needed
  @ffi.Int()
  external int iMaxBitrate;

  /// the maximum QP encoder supports
  @ffi.Int()
  external int iMaxQp;

  /// the minmum QP encoder supports
  @ffi.Int()
  external int iMinQp;

  /// the maximum NAL size. This value should be not 0 for dynamic slice mode
  @ffi.UnsignedInt()
  external int uiMaxNalSize;

  /// 1: on, 0: off
  @ffi.Bool()
  external bool bEnableLongTermReference;

  /// the number of LTR(long term reference),TODO: not supported to set it
  /// arbitrary yet
  @ffi.Int()
  external int iLTRRefNum;

  /// the LTR marked period that is used in feedback.
  @ffi.UnsignedInt()
  external int iLtrMarkPeriod;

  /// 1 # 0: auto(dynamic imp. internal encoder); 1: multiple threads imp.
  /// disabled; lager than 1: count number of threads;
  @ffi.UnsignedShort()
  external int iMultipleThreadIdc;

  /// only used when uiSliceMode=1 or 3, will change slicing of a picture during
  /// the run-time of multi-thread encoding, so the result of each run may be
  /// different
  @ffi.Bool()
  external bool bUseLoadBalancing;

  /// 0: on, 1: off, 2: on except for slice boundaries
  @ffi.Int()
  external int iLoopFilterDisableIdc;

  /// AlphaOffset: valid range [-6, 6], default 0
  @ffi.Int()
  external int iLoopFilterAlphaC0Offset;

  /// BetaOffset: valid range [-6, 6], default 0
  @ffi.Int()
  external int iLoopFilterBetaOffset;

  /// denoise control
  @ffi.Bool()
  external bool bEnableDenoise;

  /// background detection control //VAA_BACKGROUND_DETECTION //BGD cmd
  @ffi.Bool()
  external bool bEnableBackgroundDetection;

  /// adaptive quantization control
  @ffi.Bool()
  external bool bEnableAdaptiveQuant;

  /// enable frame cropping flag: TRUE always in application
  @ffi.Bool()
  external bool bEnableFrameCroppingFlag;

  @ffi.Bool()
  external bool bEnableSceneChangeDetect;

  /// LTR advanced setting
  @ffi.Bool()
  external bool bIsLosslessLink;

  /// fix rate control overshooting
  @ffi.Bool()
  external bool bFixRCOverShoot;

  /// the target bits of IDR is (idr_bitrate_ratio/100) * average target bit per
  /// frame.
  @ffi.Int()
  external int iIdrBitrateRatio;
}

/// SVC Encoding Parameters extention
typedef SEncParamExt = TagEncParamExt;

/// Define a new struct to show the property of video bitstream.
final class SVideoProperty extends ffi.Struct {
  /// size of the struct
  @ffi.UnsignedInt()
  external int size;

  /// video stream type (AVC/SVC)
  @ffi.UnsignedInt()
  external int eVideoBsTypeAsInt;

  VIDEO_BITSTREAM_TYPE get eVideoBsType =>
      VIDEO_BITSTREAM_TYPE.fromValue(eVideoBsTypeAsInt);
}

/// SVC Decoding Parameters, reserved here and potential applicable in the
/// future
final class TagSVCDecodingParam extends ffi.Struct {
  /// file name of reconstructed frame used for PSNR calculation based debug
  external ffi.Pointer<ffi.Char> pFileNameRestructed;

  /// CPU load
  @ffi.UnsignedInt()
  external int uiCpuLoad;

  /// setting target dq layer id
  @ffi.UnsignedChar()
  external int uiTargetDqLayer;

  /// whether active error concealment feature in decoder
  @ffi.UnsignedInt()
  external int eEcActiveIdcAsInt;

  ERROR_CON_IDC get eEcActiveIdc => ERROR_CON_IDC.fromValue(eEcActiveIdcAsInt);

  /// decoder for parse only, no reconstruction. When it is true, SPS/PPS size
  /// should not exceed SPS_PPS_BS_SIZE (128). Otherwise, it will return error
  /// info
  @ffi.Bool()
  external bool bParseOnly;

  /// video stream property
  external SVideoProperty sVideoProperty;
}

/// SVC Decoding Parameters, reserved here and potential applicable in the
/// future
typedef SDecodingParam = TagSVCDecodingParam;
typedef PDecodingParam = ffi.Pointer<TagSVCDecodingParam>;

/// Bitstream inforamtion of a layer being encoded
final class SLayerBSInfo extends ffi.Struct {
  @ffi.UnsignedChar()
  external int uiTemporalId;

  @ffi.UnsignedChar()
  external int uiSpatialId;

  @ffi.UnsignedChar()
  external int uiQualityId;

  @ffi.UnsignedInt()
  external int eFrameTypeAsInt;

  EVideoFrameType get eFrameType => EVideoFrameType.fromValue(eFrameTypeAsInt);

  @ffi.UnsignedChar()
  external int uiLayerType;

  /// refer to D.2.11 Sub-sequence information SEI message semantics
  @ffi.Int()
  external int iSubSeqId;

  /// count number of NAL coded already
  @ffi.Int()
  external int iNalCount;

  /// length of NAL size in byte from 0 to iNalCount-1
  external ffi.Pointer<ffi.Int> pNalLengthInByte;

  /// buffer of bitstream contained
  external ffi.Pointer<ffi.UnsignedChar> pBsBuf;
}

/// Bitstream inforamtion of a layer being encoded
typedef PLayerBSInfo = ffi.Pointer<SLayerBSInfo>;

/// Frame bit stream info
final class SFrameBSInfo extends ffi.Struct {
  @ffi.Int()
  external int iLayerNum;

  @ffi.Array.multi([128])
  external ffi.Array<SLayerBSInfo> sLayerInfo;

  @ffi.UnsignedInt()
  external int eFrameTypeAsInt;

  EVideoFrameType get eFrameType => EVideoFrameType.fromValue(eFrameTypeAsInt);

  @ffi.Int()
  external int iFrameSizeInBytes;

  @ffi.LongLong()
  external int uiTimeStamp;
}

/// Frame bit stream info
typedef PFrameBSInfo = ffi.Pointer<SFrameBSInfo>;

/// Structure for source picture
final class Source_Picture_s extends ffi.Struct {
  /// color space type
  @ffi.Int()
  external int iColorFormat;

  /// stride for each plane pData
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Int> iStride;

  /// plane pData
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Pointer<ffi.UnsignedChar>> pData;

  /// luma picture width in x coordinate
  @ffi.Int()
  external int iPicWidth;

  /// luma picture height in y coordinate
  @ffi.Int()
  external int iPicHeight;

  /// timestamp of the source picture, unit: millisecond
  @ffi.LongLong()
  external int uiTimeStamp;
}

/// Structure for source picture
typedef SSourcePicture = Source_Picture_s;

/// Structure for bit rate info
final class TagBitrateInfo extends ffi.Struct {
  @ffi.UnsignedInt()
  external int iLayerAsInt;

  LAYER_NUM get iLayer => LAYER_NUM.fromValue(iLayerAsInt);

  /// the maximum bitrate
  @ffi.Int()
  external int iBitrate;
}

/// Structure for bit rate info
typedef SBitrateInfo = TagBitrateInfo;

/// Structure for dump layer info
final class TagDumpLayer extends ffi.Struct {
  @ffi.Int()
  external int iLayer;

  external ffi.Pointer<ffi.Char> pFileName;
}

/// Structure for dump layer info
typedef SDumpLayer = TagDumpLayer;

/// Structure for profile info in layer
final class TagProfileInfo extends ffi.Struct {
  @ffi.Int()
  external int iLayer;

  /// the profile info
  @ffi.UnsignedInt()
  external int uiProfileIdcAsInt;

  EProfileIdc get uiProfileIdc => EProfileIdc.fromValue(uiProfileIdcAsInt);
}

/// Structure for profile info in layer
typedef SProfileInfo = TagProfileInfo;

/// Structure for level info in layer
final class TagLevelInfo extends ffi.Struct {
  @ffi.Int()
  external int iLayer;

  /// the level info
  @ffi.UnsignedInt()
  external int uiLevelIdcAsInt;

  ELevelIdc get uiLevelIdc => ELevelIdc.fromValue(uiLevelIdcAsInt);
}

/// Structure for level info in layer
typedef SLevelInfo = TagLevelInfo;

/// Structure for dilivery status
final class TagDeliveryStatus extends ffi.Struct {
  /// 0: the previous frame isn't delivered,1: the previous frame is delivered
  @ffi.Bool()
  external bool bDeliveryFlag;

  /// the frame type that is dropped; reserved
  @ffi.Int()
  external int iDropFrameType;

  /// the frame size that is dropped; reserved
  @ffi.Int()
  external int iDropFrameSize;
}

/// Structure for dilivery status
typedef SDeliveryStatus = TagDeliveryStatus;

/// The capability of decoder, for SDP negotiation
final class TagDecoderCapability extends ffi.Struct {
  /// profile_idc
  @ffi.Int()
  external int iProfileIdc;

  /// profile-iop
  @ffi.Int()
  external int iProfileIop;

  /// level_idc
  @ffi.Int()
  external int iLevelIdc;

  /// max-mbps
  @ffi.Int()
  external int iMaxMbps;

  /// max-fs
  @ffi.Int()
  external int iMaxFs;

  /// max-cpb
  @ffi.Int()
  external int iMaxCpb;

  /// max-dpb
  @ffi.Int()
  external int iMaxDpb;

  /// max-br
  @ffi.Int()
  external int iMaxBr;

  /// redundant-pic-cap
  @ffi.Bool()
  external bool bRedPicCap;
}

/// The capability of decoder, for SDP negotiation
typedef SDecoderCapability = TagDecoderCapability;

/// Structure for parse only output
final class TagParserBsInfo extends ffi.Struct {
  /// total NAL number in current AU
  @ffi.Int()
  external int iNalNum;

  /// each nal length
  external ffi.Pointer<ffi.Int> pNalLenInByte;

  /// outputted dst buffer for parsed bitstream
  external ffi.Pointer<ffi.UnsignedChar> pDstBuff;

  /// required SPS width info
  @ffi.Int()
  external int iSpsWidthInPixel;

  /// required SPS height info
  @ffi.Int()
  external int iSpsHeightInPixel;

  /// input BS timestamp
  @ffi.UnsignedLongLong()
  external int uiInBsTimeStamp;

  /// output BS timestamp
  @ffi.UnsignedLongLong()
  external int uiOutBsTimeStamp;
}

/// Structure for parse only output
typedef SParserBsInfo = TagParserBsInfo;
typedef PParserBsInfo = ffi.Pointer<TagParserBsInfo>;

/// Structure for encoder statistics
final class TagVideoEncoderStatistics extends ffi.Struct {
  /// the width of encoded frame
  @ffi.UnsignedInt()
  external int uiWidth;

  /// the height of encoded frame
  @ffi.UnsignedInt()
  external int uiHeight;

  /// average_Encoding_Time
  @ffi.Float()
  external double fAverageFrameSpeedInMs;

  /// the average frame rate in, calculate since encoding starts, supposed that
  /// the input timestamp is in unit of ms
  @ffi.Float()
  external double fAverageFrameRate;

  /// the frame rate in, in the last second, supposed that the input timestamp
  /// is in unit of ms (? useful for checking BR, but is it easy to calculate?
  @ffi.Float()
  external double fLatestFrameRate;

  /// sendrate in Bits per second, calculated within the set time-window
  @ffi.UnsignedInt()
  external int uiBitRate;

  /// the average QP of last encoded frame
  @ffi.UnsignedInt()
  external int uiAverageFrameQP;

  /// number of frames
  @ffi.UnsignedInt()
  external int uiInputFrameCount;

  /// number of frames
  @ffi.UnsignedInt()
  external int uiSkippedFrameCount;

  /// uiResolutionChangeTimes
  @ffi.UnsignedInt()
  external int uiResolutionChangeTimes;

  /// number of IDR requests
  @ffi.UnsignedInt()
  external int uiIDRReqNum;

  /// number of actual IDRs sent
  @ffi.UnsignedInt()
  external int uiIDRSentNum;

  /// number of LTR sent/marked
  @ffi.UnsignedInt()
  external int uiLTRSentNum;

  /// Timestamp of updating the statistics
  @ffi.LongLong()
  external int iStatisticsTs;

  @ffi.UnsignedLong()
  external int iTotalEncodedBytes;

  @ffi.UnsignedLong()
  external int iLastStatisticsBytes;

  @ffi.UnsignedLong()
  external int iLastStatisticsFrameCount;
}

/// Structure for encoder statistics
typedef SEncoderStatistics = TagVideoEncoderStatistics;

/// Structure for decoder statistics
final class TagVideoDecoderStatistics extends ffi.Struct {
  /// the width of encode/decode frame
  @ffi.UnsignedInt()
  external int uiWidth;

  /// the height of encode/decode frame
  @ffi.UnsignedInt()
  external int uiHeight;

  /// average_Decoding_Time
  @ffi.Float()
  external double fAverageFrameSpeedInMs;

  /// actual average_Decoding_Time, including freezing pictures
  @ffi.Float()
  external double fActualAverageFrameSpeedInMs;

  /// number of frames
  @ffi.UnsignedInt()
  external int uiDecodedFrameCount;

  /// uiResolutionChangeTimes
  @ffi.UnsignedInt()
  external int uiResolutionChangeTimes;

  /// number of correct IDR received
  @ffi.UnsignedInt()
  external int uiIDRCorrectNum;

  /// when EC is on, the average ratio of total EC areas, can be an indicator of
  /// reconstruction quality
  @ffi.UnsignedInt()
  external int uiAvgEcRatio;

  /// when EC is on, the rough average ratio of propogate EC areas, can be an
  /// indicator of reconstruction quality
  @ffi.UnsignedInt()
  external int uiAvgEcPropRatio;

  /// number of actual unintegrity IDR or not received but eced
  @ffi.UnsignedInt()
  external int uiEcIDRNum;

  @ffi.UnsignedInt()
  external int uiEcFrameNum;

  /// number of whole lost IDR
  @ffi.UnsignedInt()
  external int uiIDRLostNum;

  /// number of freezing IDR with error (partly received), under resolution
  /// change
  @ffi.UnsignedInt()
  external int uiFreezingIDRNum;

  /// number of freezing non-IDR with error
  @ffi.UnsignedInt()
  external int uiFreezingNonIDRNum;

  /// average luma QP. default: -1, no correct frame outputted
  @ffi.Int()
  external int iAvgLumaQp;

  /// number of Sps Invalid report
  @ffi.Int()
  external int iSpsReportErrorNum;

  /// number of SubSps Invalid report
  @ffi.Int()
  external int iSubSpsReportErrorNum;

  /// number of Pps Invalid report
  @ffi.Int()
  external int iPpsReportErrorNum;

  /// number of Sps NoExist Nal
  @ffi.Int()
  external int iSpsNoExistNalNum;

  /// number of SubSps NoExist Nal
  @ffi.Int()
  external int iSubSpsNoExistNalNum;

  /// number of Pps NoExist Nal
  @ffi.Int()
  external int iPpsNoExistNalNum;

  /// Profile idc in syntax
  @ffi.UnsignedInt()
  external int uiProfile;

  /// level idc according to Annex A-1
  @ffi.UnsignedInt()
  external int uiLevel;

  /// current active SPS id
  @ffi.Int()
  external int iCurrentActiveSpsId;

  /// current active PPS id
  @ffi.Int()
  external int iCurrentActivePpsId;

  /// frame interval of statistics log
  @ffi.UnsignedInt()
  external int iStatisticsLogInterval;
}

/// Structure for decoder statistics
typedef SDecoderStatistics = TagVideoDecoderStatistics;

/// Structure for sample aspect ratio (SAR) info in VUI
final class TagVuiSarInfo extends ffi.Struct {
  /// SAR width
  @ffi.UnsignedInt()
  external int uiSarWidth;

  /// SAR height
  @ffi.UnsignedInt()
  external int uiSarHeight;

  /// SAR overscan flag
  @ffi.Bool()
  external bool bOverscanAppropriateFlag;
}

/// Structure for sample aspect ratio (SAR) info in VUI
typedef SVuiSarInfo = TagVuiSarInfo;
typedef PVuiSarInfo = ffi.Pointer<TagVuiSarInfo>;
typedef ISVCEncoder = ffi.Pointer<ISVCEncoderVtbl>;

final class ISVCEncoderVtbl extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ISVCEncoder>, ffi.Pointer<SEncParamBase>)
    >
  >
  Initialize;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ISVCEncoder>, ffi.Pointer<SEncParamExt>)
    >
  >
  InitializeExt;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ISVCEncoder>, ffi.Pointer<SEncParamExt>)
    >
  >
  GetDefaultParams;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ISVCEncoder>)>
  >
  Uninitialize;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ISVCEncoder>,
        ffi.Pointer<SSourcePicture>,
        ffi.Pointer<SFrameBSInfo>,
      )
    >
  >
  EncodeFrame;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ISVCEncoder>, ffi.Pointer<SFrameBSInfo>)
    >
  >
  EncodeParameterSets;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ISVCEncoder>, ffi.Bool)>
  >
  ForceIntraFrame;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ISVCEncoder>,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Void>,
      )
    >
  >
  SetOption;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(
        ffi.Pointer<ISVCEncoder>,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Void>,
      )
    >
  >
  GetOption;
}

typedef ISVCDecoder = ffi.Pointer<ISVCDecoderVtbl>;

final class ISVCDecoderVtbl extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Long Function(ffi.Pointer<ISVCDecoder>, ffi.Pointer<SDecodingParam>)
    >
  >
  Initialize;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ISVCDecoder>)>
  >
  Uninitialize;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
      )
    >
  >
  DecodeFrame;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
        ffi.Pointer<SBufferInfo>,
      )
    >
  >
  DecodeFrameNoDelay;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
        ffi.Pointer<SBufferInfo>,
      )
    >
  >
  DecodeFrame2;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
        ffi.Pointer<SBufferInfo>,
      )
    >
  >
  FlushFrame;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<SParserBsInfo>,
      )
    >
  >
  DecodeParser;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<ffi.UnsignedChar>,
        ffi.Int,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
        ffi.Pointer<ffi.Int>,
      )
    >
  >
  DecodeFrameEx;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Long Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Void>,
      )
    >
  >
  SetOption;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Long Function(
        ffi.Pointer<ISVCDecoder>,
        ffi.UnsignedInt,
        ffi.Pointer<ffi.Void>,
      )
    >
  >
  GetOption;
}

typedef WelsTraceCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Int level,
      ffi.Pointer<ffi.Char> string,
    );
typedef DartWelsTraceCallbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> ctx,
      int level,
      ffi.Pointer<ffi.Char> string,
    );
typedef WelsTraceCallback =
    ffi.Pointer<ffi.NativeFunction<WelsTraceCallbackFunction>>;

const int DEBLOCKING_IDC_0 = 0;

const int DEBLOCKING_IDC_1 = 1;

const int DEBLOCKING_IDC_2 = 2;

const int ET_NONE = 0;

const int ET_IP_SCALE = 1;

const int ET_FMO = 2;

const int ET_IR_R1 = 4;

const int ET_IR_R2 = 8;

const int ET_IR_R3 = 16;

const int ET_FEC_HALF = 32;

const int ET_FEC_FULL = 64;

const int ET_RFS = 128;

const int WELS_LOG_QUIET = 0;

const int WELS_LOG_ERROR = 1;

const int WELS_LOG_WARNING = 2;

const int WELS_LOG_INFO = 4;

const int WELS_LOG_DEBUG = 8;

const int WELS_LOG_DETAIL = 16;

const int WELS_LOG_RESV = 32;

const int WELS_LOG_LEVEL_COUNT = 6;

const int WELS_LOG_DEFAULT = 2;

const int DEBLOCKING_IDC_0$1 = 0;

const int DEBLOCKING_IDC_1$1 = 1;

const int DEBLOCKING_IDC_2$1 = 2;

const int ET_NONE$1 = 0;

const int ET_IP_SCALE$1 = 1;

const int ET_FMO$1 = 2;

const int ET_IR_R1$1 = 4;

const int ET_IR_R2$1 = 8;

const int ET_IR_R3$1 = 16;

const int ET_FEC_HALF$1 = 32;

const int ET_FEC_FULL$1 = 64;

const int ET_RFS$1 = 128;

const int WELS_LOG_QUIET$1 = 0;

const int WELS_LOG_ERROR$1 = 1;

const int WELS_LOG_WARNING$1 = 2;

const int WELS_LOG_INFO$1 = 4;

const int WELS_LOG_DEBUG$1 = 8;

const int WELS_LOG_DETAIL$1 = 16;

const int WELS_LOG_RESV$1 = 32;

const int WELS_LOG_LEVEL_COUNT$1 = 6;

const int WELS_LOG_DEFAULT$1 = 2;

const int DEBLOCKING_IDC_0$2 = 0;

const int DEBLOCKING_IDC_1$2 = 1;

const int DEBLOCKING_IDC_2$2 = 2;

const int ET_NONE$2 = 0;

const int ET_IP_SCALE$2 = 1;

const int ET_FMO$2 = 2;

const int ET_IR_R1$2 = 4;

const int ET_IR_R2$2 = 8;

const int ET_IR_R3$2 = 16;

const int ET_FEC_HALF$2 = 32;

const int ET_FEC_FULL$2 = 64;

const int ET_RFS$2 = 128;

const int DEBLOCKING_IDC_0$3 = 0;

const int DEBLOCKING_IDC_1$3 = 1;

const int DEBLOCKING_IDC_2$3 = 2;

const int ET_NONE$3 = 0;

const int ET_IP_SCALE$3 = 1;

const int ET_FMO$3 = 2;

const int ET_IR_R1$3 = 4;

const int ET_IR_R2$3 = 8;

const int ET_IR_R3$3 = 16;

const int ET_FEC_HALF$3 = 32;

const int ET_FEC_FULL$3 = 64;

const int ET_RFS$3 = 128;

const int WELS_LOG_QUIET$2 = 0;

const int WELS_LOG_ERROR$2 = 1;

const int WELS_LOG_WARNING$2 = 2;

const int WELS_LOG_INFO$2 = 4;

const int WELS_LOG_DEBUG$2 = 8;

const int WELS_LOG_DETAIL$2 = 16;

const int WELS_LOG_RESV$2 = 32;

const int WELS_LOG_LEVEL_COUNT$2 = 6;

const int WELS_LOG_DEFAULT$2 = 2;
