// ignore_for_file: type=lint, type=warning, unused_field, unused_element, non_constant_identifier_names
// Generated by ffigen. Do not edit manually.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for libopus (Xiph.org's reference Opus encoder/decoder, RFC 6716).
/// Generated via: dart run ffigen --config tool/ffigen_opus.yaml
///
class OpusBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OpusBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OpusBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Converts an opus error code into a human readable string.
  ffi.Pointer<ffi.Char> opus_strerror(int error) {
    return _opus_strerror(error);
  }

  late final _opus_strerrorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'opus_strerror',
      );
  late final _opus_strerror = _opus_strerrorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  /// Gets the libopus version string.
  ffi.Pointer<ffi.Char> opus_get_version_string() {
    return _opus_get_version_string();
  }

  late final _opus_get_version_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'opus_get_version_string',
      );
  late final _opus_get_version_string = _opus_get_version_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Gets the size of an OpusEncoder structure.
  int opus_encoder_get_size(int channels) {
    return _opus_encoder_get_size(channels);
  }

  late final _opus_encoder_get_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'opus_encoder_get_size',
      );
  late final _opus_encoder_get_size = _opus_encoder_get_sizePtr
      .asFunction<int Function(int)>();

  /// Allocates and initializes an encoder state. There are three coding modes:
  ffi.Pointer<OpusEncoder> opus_encoder_create(
    int Fs,
    int channels,
    int application,
    ffi.Pointer<ffi.Int> error,
  ) {
    return _opus_encoder_create(Fs, channels, application, error);
  }

  late final _opus_encoder_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<OpusEncoder> Function(
            opus_int32,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('opus_encoder_create');
  late final _opus_encoder_create = _opus_encoder_createPtr
      .asFunction<
        ffi.Pointer<OpusEncoder> Function(int, int, int, ffi.Pointer<ffi.Int>)
      >();

  /// Initializes a previously allocated encoder state The memory pointed to by
  /// st must be at least the size returned by opus_encoder_get_size(). This is
  /// intended for applications which use their own allocator instead of malloc.
  int opus_encoder_init(
    ffi.Pointer<OpusEncoder> st,
    int Fs,
    int channels,
    int application,
  ) {
    return _opus_encoder_init(st, Fs, channels, application);
  }

  late final _opus_encoder_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<OpusEncoder>,
            opus_int32,
            ffi.Int,
            ffi.Int,
          )
        >
      >('opus_encoder_init');
  late final _opus_encoder_init = _opus_encoder_initPtr
      .asFunction<int Function(ffi.Pointer<OpusEncoder>, int, int, int)>();

  /// Encodes an Opus frame.
  int opus_encode(
    ffi.Pointer<OpusEncoder> st,
    ffi.Pointer<opus_int16> pcm,
    int frame_size,
    ffi.Pointer<ffi.UnsignedChar> data,
    int max_data_bytes,
  ) {
    return _opus_encode(st, pcm, frame_size, data, max_data_bytes);
  }

  late final _opus_encodePtr =
      _lookup<
        ffi.NativeFunction<
          opus_int32 Function(
            ffi.Pointer<OpusEncoder>,
            ffi.Pointer<opus_int16>,
            ffi.Int,
            ffi.Pointer<ffi.UnsignedChar>,
            opus_int32,
          )
        >
      >('opus_encode');
  late final _opus_encode = _opus_encodePtr
      .asFunction<
        int Function(
          ffi.Pointer<OpusEncoder>,
          ffi.Pointer<opus_int16>,
          int,
          ffi.Pointer<ffi.UnsignedChar>,
          int,
        )
      >();

  /// Encodes an Opus frame from floating point input.
  int opus_encode_float(
    ffi.Pointer<OpusEncoder> st,
    ffi.Pointer<ffi.Float> pcm,
    int frame_size,
    ffi.Pointer<ffi.UnsignedChar> data,
    int max_data_bytes,
  ) {
    return _opus_encode_float(st, pcm, frame_size, data, max_data_bytes);
  }

  late final _opus_encode_floatPtr =
      _lookup<
        ffi.NativeFunction<
          opus_int32 Function(
            ffi.Pointer<OpusEncoder>,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Pointer<ffi.UnsignedChar>,
            opus_int32,
          )
        >
      >('opus_encode_float');
  late final _opus_encode_float = _opus_encode_floatPtr
      .asFunction<
        int Function(
          ffi.Pointer<OpusEncoder>,
          ffi.Pointer<ffi.Float>,
          int,
          ffi.Pointer<ffi.UnsignedChar>,
          int,
        )
      >();

  /// Frees an OpusEncoder allocated by opus_encoder_create().
  void opus_encoder_destroy(ffi.Pointer<OpusEncoder> st) {
    return _opus_encoder_destroy(st);
  }

  late final _opus_encoder_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<OpusEncoder>)>>(
        'opus_encoder_destroy',
      );
  late final _opus_encoder_destroy = _opus_encoder_destroyPtr
      .asFunction<void Function(ffi.Pointer<OpusEncoder>)>();

  /// Perform a CTL function on an Opus encoder.
  int opus_encoder_ctl(ffi.Pointer<OpusEncoder> st, int request) {
    return _opus_encoder_ctl(st, request);
  }

  late final _opus_encoder_ctlPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<OpusEncoder>, ffi.Int)>
      >('opus_encoder_ctl');
  late final _opus_encoder_ctl = _opus_encoder_ctlPtr
      .asFunction<int Function(ffi.Pointer<OpusEncoder>, int)>();

  /// Gets the size of an OpusDecoder structure.
  int opus_decoder_get_size(int channels) {
    return _opus_decoder_get_size(channels);
  }

  late final _opus_decoder_get_sizePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
        'opus_decoder_get_size',
      );
  late final _opus_decoder_get_size = _opus_decoder_get_sizePtr
      .asFunction<int Function(int)>();

  /// Allocates and initializes a decoder state.
  ffi.Pointer<OpusDecoder> opus_decoder_create(
    int Fs,
    int channels,
    ffi.Pointer<ffi.Int> error,
  ) {
    return _opus_decoder_create(Fs, channels, error);
  }

  late final _opus_decoder_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<OpusDecoder> Function(
            opus_int32,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('opus_decoder_create');
  late final _opus_decoder_create = _opus_decoder_createPtr
      .asFunction<
        ffi.Pointer<OpusDecoder> Function(int, int, ffi.Pointer<ffi.Int>)
      >();

  /// Initializes a previously allocated decoder state. The state must be at
  /// least the size returned by opus_decoder_get_size(). This is intended for
  /// applications which use their own allocator instead of malloc.
  int opus_decoder_init(ffi.Pointer<OpusDecoder> st, int Fs, int channels) {
    return _opus_decoder_init(st, Fs, channels);
  }

  late final _opus_decoder_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<OpusDecoder>, opus_int32, ffi.Int)
        >
      >('opus_decoder_init');
  late final _opus_decoder_init = _opus_decoder_initPtr
      .asFunction<int Function(ffi.Pointer<OpusDecoder>, int, int)>();

  /// Decode an Opus packet.
  int opus_decode(
    ffi.Pointer<OpusDecoder> st,
    ffi.Pointer<ffi.UnsignedChar> data,
    int len,
    ffi.Pointer<opus_int16> pcm,
    int frame_size,
    int decode_fec,
  ) {
    return _opus_decode(st, data, len, pcm, frame_size, decode_fec);
  }

  late final _opus_decodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<OpusDecoder>,
            ffi.Pointer<ffi.UnsignedChar>,
            opus_int32,
            ffi.Pointer<opus_int16>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('opus_decode');
  late final _opus_decode = _opus_decodePtr
      .asFunction<
        int Function(
          ffi.Pointer<OpusDecoder>,
          ffi.Pointer<ffi.UnsignedChar>,
          int,
          ffi.Pointer<opus_int16>,
          int,
          int,
        )
      >();

  /// Decode an Opus packet with floating point output.
  int opus_decode_float(
    ffi.Pointer<OpusDecoder> st,
    ffi.Pointer<ffi.UnsignedChar> data,
    int len,
    ffi.Pointer<ffi.Float> pcm,
    int frame_size,
    int decode_fec,
  ) {
    return _opus_decode_float(st, data, len, pcm, frame_size, decode_fec);
  }

  late final _opus_decode_floatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<OpusDecoder>,
            ffi.Pointer<ffi.UnsignedChar>,
            opus_int32,
            ffi.Pointer<ffi.Float>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('opus_decode_float');
  late final _opus_decode_float = _opus_decode_floatPtr
      .asFunction<
        int Function(
          ffi.Pointer<OpusDecoder>,
          ffi.Pointer<ffi.UnsignedChar>,
          int,
          ffi.Pointer<ffi.Float>,
          int,
          int,
        )
      >();

  /// Perform a CTL function on an Opus decoder.
  int opus_decoder_ctl(ffi.Pointer<OpusDecoder> st, int request) {
    return _opus_decoder_ctl(st, request);
  }

  late final _opus_decoder_ctlPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<OpusDecoder>, ffi.Int)>
      >('opus_decoder_ctl');
  late final _opus_decoder_ctl = _opus_decoder_ctlPtr
      .asFunction<int Function(ffi.Pointer<OpusDecoder>, int)>();

  /// Frees an OpusDecoder allocated by opus_decoder_create().
  void opus_decoder_destroy(ffi.Pointer<OpusDecoder> st) {
    return _opus_decoder_destroy(st);
  }

  late final _opus_decoder_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<OpusDecoder>)>>(
        'opus_decoder_destroy',
      );
  late final _opus_decoder_destroy = _opus_decoder_destroyPtr
      .asFunction<void Function(ffi.Pointer<OpusDecoder>)>();

  /// Gets the number of samples of an Opus packet.
  int opus_decoder_get_nb_samples(
    ffi.Pointer<OpusDecoder> dec,
    ffi.Pointer<ffi.UnsignedChar> packet,
    int len,
  ) {
    return _opus_decoder_get_nb_samples(dec, packet, len);
  }

  late final _opus_decoder_get_nb_samplesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<OpusDecoder>,
            ffi.Pointer<ffi.UnsignedChar>,
            opus_int32,
          )
        >
      >('opus_decoder_get_nb_samples');
  late final _opus_decoder_get_nb_samples = _opus_decoder_get_nb_samplesPtr
      .asFunction<
        int Function(
          ffi.Pointer<OpusDecoder>,
          ffi.Pointer<ffi.UnsignedChar>,
          int,
        )
      >();
}

typedef opus_int8 = ffi.Int8;
typedef Dartopus_int8 = int;
typedef opus_uint8 = ffi.Uint8;
typedef Dartopus_uint8 = int;
typedef opus_int16 = ffi.Int16;
typedef Dartopus_int16 = int;
typedef opus_uint16 = ffi.Uint16;
typedef Dartopus_uint16 = int;
typedef opus_int32 = ffi.Int32;
typedef Dartopus_int32 = int;
typedef opus_uint32 = ffi.Uint32;
typedef Dartopus_uint32 = int;
typedef opus_int64 = ffi.Int64;
typedef Dartopus_int64 = int;
typedef opus_uint64 = ffi.Uint64;
typedef Dartopus_uint64 = int;

final class OpusEncoder extends ffi.Opaque {}

final class OpusDecoder extends ffi.Opaque {}

const int OPUS_OK = 0;

const int OPUS_BAD_ARG = -1;

const int OPUS_BUFFER_TOO_SMALL = -2;

const int OPUS_INTERNAL_ERROR = -3;

const int OPUS_INVALID_PACKET = -4;

const int OPUS_UNIMPLEMENTED = -5;

const int OPUS_INVALID_STATE = -6;

const int OPUS_ALLOC_FAIL = -7;

const int OPUS_SET_APPLICATION_REQUEST = 4000;

const int OPUS_GET_APPLICATION_REQUEST = 4001;

const int OPUS_SET_BITRATE_REQUEST = 4002;

const int OPUS_GET_BITRATE_REQUEST = 4003;

const int OPUS_SET_MAX_BANDWIDTH_REQUEST = 4004;

const int OPUS_GET_MAX_BANDWIDTH_REQUEST = 4005;

const int OPUS_SET_VBR_REQUEST = 4006;

const int OPUS_GET_VBR_REQUEST = 4007;

const int OPUS_SET_BANDWIDTH_REQUEST = 4008;

const int OPUS_GET_BANDWIDTH_REQUEST = 4009;

const int OPUS_SET_COMPLEXITY_REQUEST = 4010;

const int OPUS_GET_COMPLEXITY_REQUEST = 4011;

const int OPUS_SET_INBAND_FEC_REQUEST = 4012;

const int OPUS_GET_INBAND_FEC_REQUEST = 4013;

const int OPUS_SET_PACKET_LOSS_PERC_REQUEST = 4014;

const int OPUS_GET_PACKET_LOSS_PERC_REQUEST = 4015;

const int OPUS_SET_DTX_REQUEST = 4016;

const int OPUS_GET_DTX_REQUEST = 4017;

const int OPUS_SET_VBR_CONSTRAINT_REQUEST = 4020;

const int OPUS_GET_VBR_CONSTRAINT_REQUEST = 4021;

const int OPUS_SET_FORCE_CHANNELS_REQUEST = 4022;

const int OPUS_GET_FORCE_CHANNELS_REQUEST = 4023;

const int OPUS_SET_SIGNAL_REQUEST = 4024;

const int OPUS_GET_SIGNAL_REQUEST = 4025;

const int OPUS_GET_LOOKAHEAD_REQUEST = 4027;

const int OPUS_GET_SAMPLE_RATE_REQUEST = 4029;

const int OPUS_GET_FINAL_RANGE_REQUEST = 4031;

const int OPUS_GET_PITCH_REQUEST = 4033;

const int OPUS_SET_GAIN_REQUEST = 4034;

const int OPUS_GET_GAIN_REQUEST = 4045;

const int OPUS_SET_LSB_DEPTH_REQUEST = 4036;

const int OPUS_GET_LSB_DEPTH_REQUEST = 4037;

const int OPUS_GET_LAST_PACKET_DURATION_REQUEST = 4039;

const int OPUS_SET_EXPERT_FRAME_DURATION_REQUEST = 4040;

const int OPUS_GET_EXPERT_FRAME_DURATION_REQUEST = 4041;

const int OPUS_SET_PREDICTION_DISABLED_REQUEST = 4042;

const int OPUS_GET_PREDICTION_DISABLED_REQUEST = 4043;

const int OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST = 4046;

const int OPUS_GET_PHASE_INVERSION_DISABLED_REQUEST = 4047;

const int OPUS_GET_IN_DTX_REQUEST = 4049;

const int OPUS_AUTO = -1000;

const int OPUS_BITRATE_MAX = -1;

const int OPUS_APPLICATION_VOIP = 2048;

const int OPUS_APPLICATION_AUDIO = 2049;

const int OPUS_APPLICATION_RESTRICTED_LOWDELAY = 2051;

const int OPUS_SIGNAL_VOICE = 3001;

const int OPUS_SIGNAL_MUSIC = 3002;

const int OPUS_BANDWIDTH_NARROWBAND = 1101;

const int OPUS_BANDWIDTH_MEDIUMBAND = 1102;

const int OPUS_BANDWIDTH_WIDEBAND = 1103;

const int OPUS_BANDWIDTH_SUPERWIDEBAND = 1104;

const int OPUS_BANDWIDTH_FULLBAND = 1105;

const int OPUS_FRAMESIZE_ARG = 5000;

const int OPUS_FRAMESIZE_2_5_MS = 5001;

const int OPUS_FRAMESIZE_5_MS = 5002;

const int OPUS_FRAMESIZE_10_MS = 5003;

const int OPUS_FRAMESIZE_20_MS = 5004;

const int OPUS_FRAMESIZE_40_MS = 5005;

const int OPUS_FRAMESIZE_60_MS = 5006;

const int OPUS_FRAMESIZE_80_MS = 5007;

const int OPUS_FRAMESIZE_100_MS = 5008;

const int OPUS_FRAMESIZE_120_MS = 5009;

const int OPUS_RESET_STATE = 4028;
