import 'dart:math';
import 'dart:typed_data';

import 'package:test/test.dart';
import 'package:webdartc/core/types.dart';
import 'package:webdartc/crypto/ecdsa.dart';
import 'package:webdartc/dtls/handshake.dart';
import 'package:webdartc/dtls/state_machine.dart';

/// Simulated lossy channel between two DTLS state machines.
///
/// Delivers packets between client and server, randomly dropping packets
/// based on [lossRate]. Pending retransmission timeouts are tracked and
/// can be fired to simulate timer expiry.
final class LossyChannel {
  final DtlsStateMachine client;
  final DtlsStateMachine server;
  final double lossRate;
  final Random _rng;

  int droppedCount = 0;
  int deliveredCount = 0;

  /// Pending timeouts: (fireTime, stateMachine, token).
  final List<_PendingTimeout> _timeouts = [];

  LossyChannel({
    required this.client,
    required this.server,
    required this.lossRate,
    int? seed,
  }) : _rng = Random(seed);

  /// Deliver output packets from a ProcessResult, applying packet loss.
  /// Returns any new output packets generated by the receiving side.
  void deliverResult(
    DtlsStateMachine sender,
    ProcessResult result,
  ) {
    // Schedule timeout if present.
    if (result.nextTimeout != null) {
      final t = result.nextTimeout!;
      _timeouts.add(_PendingTimeout(t.at, sender, t.token));
    }

    final receiver = sender == client ? server : client;
    final senderIp = sender == client ? '10.0.0.1' : '10.0.0.2';
    final senderPort = sender == client ? 5000 : 5001;

    for (final pkt in result.outputPackets) {
      if (lossRate > 0 && _rng.nextDouble() < lossRate) {
        droppedCount++;
        continue;
      }
      deliveredCount++;

      final r = receiver.processInput(
        pkt.data,
        remoteIp: senderIp,
        remotePort: senderPort,
      );
      if (r.isOk) {
        deliverResult(receiver, r.value);
      }
    }
  }

  /// Fire the earliest pending timeout and deliver resulting packets.
  /// Returns true if a timeout was fired, false if none pending.
  bool fireNextTimeout() {
    if (_timeouts.isEmpty) return false;

    // Sort by time and fire earliest.
    _timeouts.sort((a, b) => a.at.compareTo(b.at));
    final pending = _timeouts.removeAt(0);

    final r = pending.owner.handleTimeout(pending.token);
    if (r.isOk) {
      deliverResult(pending.owner, r.value);
    }
    return true;
  }

  /// Fire all pending timeouts (up to [maxIterations] to avoid infinite loops).
  /// Returns total timeouts fired.
  int fireAllTimeouts({int maxIterations = 100}) {
    var fired = 0;
    while (_timeouts.isNotEmpty && fired < maxIterations) {
      fireNextTimeout();
      fired++;
    }
    return fired;
  }

  bool get hasPendingTimeouts => _timeouts.isNotEmpty;
}

final class _PendingTimeout {
  final DateTime at;
  final DtlsStateMachine owner;
  final TimerToken token;
  _PendingTimeout(this.at, this.owner, this.token);
}

void main() {
  late EcdsaCertificate clientCert;
  late EcdsaCertificate serverCert;

  setUpAll(() {
    clientCert = EcdsaCertificate.selfSigned();
    serverCert = EcdsaCertificate.selfSigned();
  });

  group('DTLS handshake with packet loss', () {
    test('completes with zero packet loss (baseline)', () {
      final client = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
      final server = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

      var clientConnected = false;
      var serverConnected = false;
      client.onConnected = (_) => clientConnected = true;
      server.onConnected = (_) => serverConnected = true;

      final channel = LossyChannel(
        client: client,
        server: server,
        lossRate: 0.0,
        seed: 42,
      );

      // Start handshake.
      final initResult = client.startHandshake(
        remoteIp: '10.0.0.2',
        remotePort: 5001,
      );
      expect(initResult.isOk, isTrue);
      channel.deliverResult(client, initResult.value);

      expect(clientConnected, isTrue,
          reason: 'Client should be connected after zero-loss handshake');
      expect(serverConnected, isTrue,
          reason: 'Server should be connected after zero-loss handshake');
      expect(client.state, equals(DtlsHandshakeState.connected));
      expect(server.state, equals(DtlsHandshakeState.connected));
      expect(channel.droppedCount, equals(0));
    });

    test('completes with 30% packet loss via retransmission', () {
      final client = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
      final server = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

      var clientConnected = false;
      var serverConnected = false;
      client.onConnected = (_) => clientConnected = true;
      server.onConnected = (_) => serverConnected = true;

      final channel = LossyChannel(
        client: client,
        server: server,
        lossRate: 0.3,
        seed: 42,
      );

      final initResult = client.startHandshake(
        remoteIp: '10.0.0.2',
        remotePort: 5001,
      );
      expect(initResult.isOk, isTrue);
      channel.deliverResult(client, initResult.value);

      // Fire retransmission timeouts until both sides connect.
      var iterations = 0;
      const maxIterations = 50;
      while ((!clientConnected || !serverConnected) &&
          iterations < maxIterations) {
        if (!channel.fireNextTimeout()) break;
        iterations++;
      }

      expect(clientConnected, isTrue,
          reason: 'Client should connect after retransmissions '
              '(dropped=${channel.droppedCount}, delivered=${channel.deliveredCount})');
      expect(serverConnected, isTrue,
          reason: 'Server should connect after retransmissions '
              '(dropped=${channel.droppedCount}, delivered=${channel.deliveredCount})');
      expect(client.state, equals(DtlsHandshakeState.connected));
      expect(server.state, equals(DtlsHandshakeState.connected));
      expect(channel.droppedCount, greaterThan(0),
          reason: 'Some packets should have been dropped');
    });

    test('completes with 50% packet loss via retransmission', () {
      // Run multiple trials with different seeds to cover various drop patterns.
      var successes = 0;
      const trials = 10;

      for (var trial = 0; trial < trials; trial++) {
        final c = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
        final s = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

        var cConn = false;
        var sConn = false;
        c.onConnected = (_) => cConn = true;
        s.onConnected = (_) => sConn = true;

        final ch = LossyChannel(
          client: c,
          server: s,
          lossRate: 0.5,
          seed: trial * 1000 + 7,
        );

        final init = c.startHandshake(remoteIp: '10.0.0.2', remotePort: 5001);
        if (init.isOk) ch.deliverResult(c, init.value);

        var iter = 0;
        while ((!cConn || !sConn) && iter < 80) {
          if (!ch.fireNextTimeout()) break;
          iter++;
        }

        if (cConn && sConn) successes++;
      }

      // At 50% loss, at least some trials should succeed with retransmission.
      expect(successes, greaterThanOrEqualTo(3),
          reason: 'At least 3 of $trials trials should complete with 50% loss '
              '(got $successes)');
    });

    test('application data exchange after lossy handshake', () {
      final client = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
      final server = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

      var clientConnected = false;
      var serverConnected = false;
      Uint8List? receivedByServer;
      Uint8List? receivedByClient;

      client.onConnected = (_) => clientConnected = true;
      server.onConnected = (_) => serverConnected = true;
      server.onApplicationData = (data) => receivedByServer = data;
      client.onApplicationData = (data) => receivedByClient = data;

      // Handshake with 20% loss.
      final channel = LossyChannel(
        client: client,
        server: server,
        lossRate: 0.2,
        seed: 123,
      );

      final initResult = client.startHandshake(
        remoteIp: '10.0.0.2',
        remotePort: 5001,
      );
      expect(initResult.isOk, isTrue);
      channel.deliverResult(client, initResult.value);

      var iterations = 0;
      while ((!clientConnected || !serverConnected) && iterations < 50) {
        if (!channel.fireNextTimeout()) break;
        iterations++;
      }

      expect(clientConnected, isTrue);
      expect(serverConnected, isTrue);

      // Send application data client → server (no loss for data phase).
      final payload = Uint8List.fromList([0x48, 0x65, 0x6C, 0x6C, 0x6F]); // "Hello"
      final sendResult = client.sendApplicationData(payload);
      expect(sendResult.isOk, isTrue);

      for (final pkt in sendResult.value.outputPackets) {
        final r = server.processInput(
          pkt.data,
          remoteIp: '10.0.0.1',
          remotePort: 5000,
        );
        expect(r.isOk, isTrue);
      }

      expect(receivedByServer, isNotNull);
      expect(receivedByServer, equals(payload));

      // Send application data server → client.
      final reply = Uint8List.fromList([0x57, 0x6F, 0x72, 0x6C, 0x64]); // "World"
      final replyResult = server.sendApplicationData(reply);
      expect(replyResult.isOk, isTrue);

      for (final pkt in replyResult.value.outputPackets) {
        final r = client.processInput(
          pkt.data,
          remoteIp: '10.0.0.2',
          remotePort: 5001,
        );
        expect(r.isOk, isTrue);
      }

      expect(receivedByClient, isNotNull);
      expect(receivedByClient, equals(reply));
    });

    test('SRTP key material matches on both sides', () {
      final client = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
      final server = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

      Uint8List? clientKeyMaterial;
      Uint8List? serverKeyMaterial;
      client.onConnected = (km) => clientKeyMaterial = km;
      server.onConnected = (km) => serverKeyMaterial = km;

      // Handshake with 20% loss.
      final channel = LossyChannel(
        client: client,
        server: server,
        lossRate: 0.2,
        seed: 42,
      );

      final init = client.startHandshake(remoteIp: '10.0.0.2', remotePort: 5001);
      expect(init.isOk, isTrue);
      channel.deliverResult(client, init.value);

      var iter = 0;
      while ((clientKeyMaterial == null || serverKeyMaterial == null) &&
          iter < 80) {
        if (!channel.fireNextTimeout()) break;
        iter++;
      }

      expect(clientKeyMaterial, isNotNull,
          reason: 'Client should have exported SRTP key material');
      expect(serverKeyMaterial, isNotNull,
          reason: 'Server should have exported SRTP key material');
      expect(clientKeyMaterial, equals(serverKeyMaterial),
          reason: 'SRTP key material must match on both sides');
    });

    test('fails gracefully when all packets are dropped', () {
      final client = DtlsStateMachine(role: DtlsRole.client, localCert: clientCert);
      final server = DtlsStateMachine(role: DtlsRole.server, localCert: serverCert);

      var clientConnected = false;
      client.onConnected = (_) => clientConnected = true;

      final channel = LossyChannel(
        client: client,
        server: server,
        lossRate: 1.0, // drop everything
        seed: 0,
      );

      final init = client.startHandshake(remoteIp: '10.0.0.2', remotePort: 5001);
      expect(init.isOk, isTrue);
      channel.deliverResult(client, init.value);

      // Fire all retransmission timeouts — should exhaust max retransmit count.
      var iter = 0;
      while (channel.hasPendingTimeouts && iter < 20) {
        channel.fireNextTimeout();
        iter++;
      }

      expect(clientConnected, isFalse);
      expect(client.state, equals(DtlsHandshakeState.failed));
      expect(channel.deliveredCount, equals(0));
    });
  });
}
