// GENERATED FILE — do not edit by hand. Regenerate with:
//   dart run tool/gen_mediacodec_bindings.dart

// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Hand-curated bindings for the Android NDK MediaCodec (AMediaCodec /
/// AMediaFormat) H.264 helper. Generated by ffigen from the NDK sysroot
/// media headers; the include lists below control what gets emitted.
///
class MediaCodecBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MediaCodecBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MediaCodecBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Available since API level 21.
  ffi.Pointer<AMediaFormat> AMediaFormat_new() {
    return _AMediaFormat_new();
  }

  late final _AMediaFormat_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<AMediaFormat> Function()>>(
        'AMediaFormat_new',
      );
  late final _AMediaFormat_new =
      _AMediaFormat_newPtr.asFunction<ffi.Pointer<AMediaFormat> Function()>();

  /// Available since API level 21.
  media_status_t AMediaFormat_delete(ffi.Pointer<AMediaFormat> arg0) {
    return media_status_t.fromValue(_AMediaFormat_delete(arg0));
  }

  late final _AMediaFormat_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMediaFormat>)>>(
        'AMediaFormat_delete',
      );
  late final _AMediaFormat_delete =
      _AMediaFormat_deletePtr.asFunction<
        int Function(ffi.Pointer<AMediaFormat>)
      >();

  /// Available since API level 21.
  bool AMediaFormat_getInt32(
    ffi.Pointer<AMediaFormat> arg0,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Int32> out,
  ) {
    return _AMediaFormat_getInt32(arg0, name, out);
  }

  late final _AMediaFormat_getInt32Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Int32>,
          )
        >
      >('AMediaFormat_getInt32');
  late final _AMediaFormat_getInt32 =
      _AMediaFormat_getInt32Ptr.asFunction<
        bool Function(
          ffi.Pointer<AMediaFormat>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Int32>,
        )
      >();

  /// The returned data is owned by the format and remains valid as long as the
  /// named entry is part of the format.
  bool AMediaFormat_getBuffer(
    ffi.Pointer<AMediaFormat> arg0,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Void>> data,
    ffi.Pointer<ffi.Size> size,
  ) {
    return _AMediaFormat_getBuffer(arg0, name, data, size);
  }

  late final _AMediaFormat_getBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('AMediaFormat_getBuffer');
  late final _AMediaFormat_getBuffer =
      _AMediaFormat_getBufferPtr.asFunction<
        bool Function(
          ffi.Pointer<AMediaFormat>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Available since API level 21.
  void AMediaFormat_setInt32(
    ffi.Pointer<AMediaFormat> arg0,
    ffi.Pointer<ffi.Char> name,
    int value,
  ) {
    return _AMediaFormat_setInt32(arg0, name, value);
  }

  late final _AMediaFormat_setInt32Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('AMediaFormat_setInt32');
  late final _AMediaFormat_setInt32 =
      _AMediaFormat_setInt32Ptr.asFunction<
        void Function(ffi.Pointer<AMediaFormat>, ffi.Pointer<ffi.Char>, int)
      >();

  /// The provided string is copied into the format.
  void AMediaFormat_setString(
    ffi.Pointer<AMediaFormat> arg0,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _AMediaFormat_setString(arg0, name, value);
  }

  late final _AMediaFormat_setStringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('AMediaFormat_setString');
  late final _AMediaFormat_setString =
      _AMediaFormat_setStringPtr.asFunction<
        void Function(
          ffi.Pointer<AMediaFormat>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// The provided data is copied into the format.
  void AMediaFormat_setBuffer(
    ffi.Pointer<AMediaFormat> arg0,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Void> data,
    int size,
  ) {
    return _AMediaFormat_setBuffer(arg0, name, data, size);
  }

  late final _AMediaFormat_setBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
          )
        >
      >('AMediaFormat_setBuffer');
  late final _AMediaFormat_setBuffer =
      _AMediaFormat_setBufferPtr.asFunction<
        void Function(
          ffi.Pointer<AMediaFormat>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Void>,
          int,
        )
      >();

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_BIT_RATE =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_BIT_RATE');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_BIT_RATE =>
      _AMEDIAFORMAT_KEY_BIT_RATE.value;

  set AMEDIAFORMAT_KEY_BIT_RATE(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_BIT_RATE.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_COLOR_FORMAT =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_COLOR_FORMAT');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_COLOR_FORMAT =>
      _AMEDIAFORMAT_KEY_COLOR_FORMAT.value;

  set AMEDIAFORMAT_KEY_COLOR_FORMAT(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_COLOR_FORMAT.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_FRAME_RATE =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_FRAME_RATE');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_FRAME_RATE =>
      _AMEDIAFORMAT_KEY_FRAME_RATE.value;

  set AMEDIAFORMAT_KEY_FRAME_RATE(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_FRAME_RATE.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_HEIGHT =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_HEIGHT');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_HEIGHT =>
      _AMEDIAFORMAT_KEY_HEIGHT.value;

  set AMEDIAFORMAT_KEY_HEIGHT(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_HEIGHT.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>>
  _AMEDIAFORMAT_KEY_I_FRAME_INTERVAL = _lookup<ffi.Pointer<ffi.Char>>(
    'AMEDIAFORMAT_KEY_I_FRAME_INTERVAL',
  );

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_I_FRAME_INTERVAL =>
      _AMEDIAFORMAT_KEY_I_FRAME_INTERVAL.value;

  set AMEDIAFORMAT_KEY_I_FRAME_INTERVAL(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_I_FRAME_INTERVAL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_MIME =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_MIME');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_MIME =>
      _AMEDIAFORMAT_KEY_MIME.value;

  set AMEDIAFORMAT_KEY_MIME(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_MIME.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_SLICE_HEIGHT =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_SLICE_HEIGHT');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_SLICE_HEIGHT =>
      _AMEDIAFORMAT_KEY_SLICE_HEIGHT.value;

  set AMEDIAFORMAT_KEY_SLICE_HEIGHT(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_SLICE_HEIGHT.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_STRIDE =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_STRIDE');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_STRIDE =>
      _AMEDIAFORMAT_KEY_STRIDE.value;

  set AMEDIAFORMAT_KEY_STRIDE(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_STRIDE.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _AMEDIAFORMAT_KEY_WIDTH =
      _lookup<ffi.Pointer<ffi.Char>>('AMEDIAFORMAT_KEY_WIDTH');

  ffi.Pointer<ffi.Char> get AMEDIAFORMAT_KEY_WIDTH =>
      _AMEDIAFORMAT_KEY_WIDTH.value;

  set AMEDIAFORMAT_KEY_WIDTH(ffi.Pointer<ffi.Char> value) =>
      _AMEDIAFORMAT_KEY_WIDTH.value = value;

  /// Create codec by mime type. Most applications will use this, specifying a
  /// mime type obtained from media extractor.
  ffi.Pointer<AMediaCodec> AMediaCodec_createDecoderByType(
    ffi.Pointer<ffi.Char> mime_type,
  ) {
    return _AMediaCodec_createDecoderByType(mime_type);
  }

  late final _AMediaCodec_createDecoderByTypePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<AMediaCodec> Function(ffi.Pointer<ffi.Char>)
        >
      >('AMediaCodec_createDecoderByType');
  late final _AMediaCodec_createDecoderByType =
      _AMediaCodec_createDecoderByTypePtr.asFunction<
        ffi.Pointer<AMediaCodec> Function(ffi.Pointer<ffi.Char>)
      >();

  /// Create encoder by name.
  ffi.Pointer<AMediaCodec> AMediaCodec_createEncoderByType(
    ffi.Pointer<ffi.Char> mime_type,
  ) {
    return _AMediaCodec_createEncoderByType(mime_type);
  }

  late final _AMediaCodec_createEncoderByTypePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<AMediaCodec> Function(ffi.Pointer<ffi.Char>)
        >
      >('AMediaCodec_createEncoderByType');
  late final _AMediaCodec_createEncoderByType =
      _AMediaCodec_createEncoderByTypePtr.asFunction<
        ffi.Pointer<AMediaCodec> Function(ffi.Pointer<ffi.Char>)
      >();

  /// Delete the codec and free its resources.
  media_status_t AMediaCodec_delete(ffi.Pointer<AMediaCodec> arg0) {
    return media_status_t.fromValue(_AMediaCodec_delete(arg0));
  }

  late final _AMediaCodec_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMediaCodec>)>>(
        'AMediaCodec_delete',
      );
  late final _AMediaCodec_delete =
      _AMediaCodec_deletePtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>)
      >();

  /// Configure the codec. For decoding you would typically get the format from
  /// an extractor.
  media_status_t AMediaCodec_configure(
    ffi.Pointer<AMediaCodec> arg0,
    ffi.Pointer<AMediaFormat> format,
    ffi.Pointer<ANativeWindow> surface,
    ffi.Pointer<AMediaCrypto> crypto,
    int flags,
  ) {
    return media_status_t.fromValue(
      _AMediaCodec_configure(arg0, format, surface, crypto, flags),
    );
  }

  late final _AMediaCodec_configurePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<AMediaCodec>,
            ffi.Pointer<AMediaFormat>,
            ffi.Pointer<ANativeWindow>,
            ffi.Pointer<AMediaCrypto>,
            ffi.Uint32,
          )
        >
      >('AMediaCodec_configure');
  late final _AMediaCodec_configure =
      _AMediaCodec_configurePtr.asFunction<
        int Function(
          ffi.Pointer<AMediaCodec>,
          ffi.Pointer<AMediaFormat>,
          ffi.Pointer<ANativeWindow>,
          ffi.Pointer<AMediaCrypto>,
          int,
        )
      >();

  /// Start the codec. A codec must be configured before it can be started, and
  /// must be started before buffers can be sent to it.
  media_status_t AMediaCodec_start(ffi.Pointer<AMediaCodec> arg0) {
    return media_status_t.fromValue(_AMediaCodec_start(arg0));
  }

  late final _AMediaCodec_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMediaCodec>)>>(
        'AMediaCodec_start',
      );
  late final _AMediaCodec_start =
      _AMediaCodec_startPtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>)
      >();

  /// Stop the codec.
  media_status_t AMediaCodec_stop(ffi.Pointer<AMediaCodec> arg0) {
    return media_status_t.fromValue(_AMediaCodec_stop(arg0));
  }

  late final _AMediaCodec_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMediaCodec>)>>(
        'AMediaCodec_stop',
      );
  late final _AMediaCodec_stop =
      _AMediaCodec_stopPtr.asFunction<int Function(ffi.Pointer<AMediaCodec>)>();

  /// Flush the codec's input and output. All indices previously returned from
  /// calls to AMediaCodec_dequeueInputBuffer and
  /// AMediaCodec_dequeueOutputBuffer become invalid.
  media_status_t AMediaCodec_flush(ffi.Pointer<AMediaCodec> arg0) {
    return media_status_t.fromValue(_AMediaCodec_flush(arg0));
  }

  late final _AMediaCodec_flushPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<AMediaCodec>)>>(
        'AMediaCodec_flush',
      );
  late final _AMediaCodec_flush =
      _AMediaCodec_flushPtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>)
      >();

  /// Get an input buffer. The specified buffer index must have been previously
  /// obtained from dequeueInputBuffer, and not yet queued.
  ffi.Pointer<ffi.Uint8> AMediaCodec_getInputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    int idx,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return _AMediaCodec_getInputBuffer(arg0, idx, out_size);
  }

  late final _AMediaCodec_getInputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(
            ffi.Pointer<AMediaCodec>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('AMediaCodec_getInputBuffer');
  late final _AMediaCodec_getInputBuffer =
      _AMediaCodec_getInputBufferPtr.asFunction<
        ffi.Pointer<ffi.Uint8> Function(
          ffi.Pointer<AMediaCodec>,
          int,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Get an output buffer. The specified buffer index must have been previously
  /// obtained from dequeueOutputBuffer, and not yet queued.
  ffi.Pointer<ffi.Uint8> AMediaCodec_getOutputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    int idx,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return _AMediaCodec_getOutputBuffer(arg0, idx, out_size);
  }

  late final _AMediaCodec_getOutputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(
            ffi.Pointer<AMediaCodec>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('AMediaCodec_getOutputBuffer');
  late final _AMediaCodec_getOutputBuffer =
      _AMediaCodec_getOutputBufferPtr.asFunction<
        ffi.Pointer<ffi.Uint8> Function(
          ffi.Pointer<AMediaCodec>,
          int,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Get the index of the next available input buffer. An app will typically
  /// use this with getInputBuffer() to get a pointer to the buffer, then copy
  /// the data to be encoded or decoded into the buffer before passing it to the
  /// codec.
  int AMediaCodec_dequeueInputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    int timeoutUs,
  ) {
    return _AMediaCodec_dequeueInputBuffer(arg0, timeoutUs);
  }

  late final _AMediaCodec_dequeueInputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(ffi.Pointer<AMediaCodec>, ffi.Int64)
        >
      >('AMediaCodec_dequeueInputBuffer');
  late final _AMediaCodec_dequeueInputBuffer =
      _AMediaCodec_dequeueInputBufferPtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>, int)
      >();

  /// Send the specified buffer to the codec for processing.
  media_status_t AMediaCodec_queueInputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    int idx,
    int offset,
    int size,
    int time,
    int flags,
  ) {
    return media_status_t.fromValue(
      _AMediaCodec_queueInputBuffer(arg0, idx, offset, size, time, flags),
    );
  }

  late final _AMediaCodec_queueInputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<AMediaCodec>,
            ffi.Size,
            ffi.Int64,
            ffi.Size,
            ffi.Uint64,
            ffi.Uint32,
          )
        >
      >('AMediaCodec_queueInputBuffer');
  late final _AMediaCodec_queueInputBuffer =
      _AMediaCodec_queueInputBufferPtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>, int, int, int, int, int)
      >();

  /// Get the index of the next available buffer of processed data along with
  /// the metadata associated with it.
  int AMediaCodec_dequeueOutputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    ffi.Pointer<AMediaCodecBufferInfo> info,
    int timeoutUs,
  ) {
    return _AMediaCodec_dequeueOutputBuffer(arg0, info, timeoutUs);
  }

  late final _AMediaCodec_dequeueOutputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Pointer<AMediaCodec>,
            ffi.Pointer<AMediaCodecBufferInfo>,
            ffi.Int64,
          )
        >
      >('AMediaCodec_dequeueOutputBuffer');
  late final _AMediaCodec_dequeueOutputBuffer =
      _AMediaCodec_dequeueOutputBufferPtr.asFunction<
        int Function(
          ffi.Pointer<AMediaCodec>,
          ffi.Pointer<AMediaCodecBufferInfo>,
          int,
        )
      >();

  /// Returns the format of the codec's output. The caller must free the
  /// returned format.
  ffi.Pointer<AMediaFormat> AMediaCodec_getOutputFormat(
    ffi.Pointer<AMediaCodec> arg0,
  ) {
    return _AMediaCodec_getOutputFormat(arg0);
  }

  late final _AMediaCodec_getOutputFormatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<AMediaFormat> Function(ffi.Pointer<AMediaCodec>)
        >
      >('AMediaCodec_getOutputFormat');
  late final _AMediaCodec_getOutputFormat =
      _AMediaCodec_getOutputFormatPtr.asFunction<
        ffi.Pointer<AMediaFormat> Function(ffi.Pointer<AMediaCodec>)
      >();

  /// If you are done with a buffer, use this call to return the buffer to the
  /// codec. If you previously specified a surface when configuring this video
  /// decoder you can optionally render the buffer.
  media_status_t AMediaCodec_releaseOutputBuffer(
    ffi.Pointer<AMediaCodec> arg0,
    int idx,
    bool render,
  ) {
    return media_status_t.fromValue(
      _AMediaCodec_releaseOutputBuffer(arg0, idx, render),
    );
  }

  late final _AMediaCodec_releaseOutputBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<AMediaCodec>, ffi.Size, ffi.Bool)
        >
      >('AMediaCodec_releaseOutputBuffer');
  late final _AMediaCodec_releaseOutputBuffer =
      _AMediaCodec_releaseOutputBufferPtr.asFunction<
        int Function(ffi.Pointer<AMediaCodec>, int, bool)
      >();
}

/// Media error message types returned from NDK media functions.
enum media_status_t {
  /// The requested media operation completed successfully.
  AMEDIA_OK(0),

  /// This indicates required resource was not able to be allocated.
  AMEDIACODEC_ERROR_INSUFFICIENT_RESOURCE(1100),

  /// This indicates the resource manager reclaimed the media resource used by
  /// the codec. With this error, the codec must be released, as it has moved to
  /// terminal state.
  AMEDIACODEC_ERROR_RECLAIMED(1101),
  AMEDIA_ERROR_BASE(-10000),

  /// The input media data is corrupt or incomplete.
  AMEDIA_ERROR_MALFORMED(-10001),

  /// The required operation or media formats are not supported.
  AMEDIA_ERROR_UNSUPPORTED(-10002),

  /// An invalid (or already closed) object is used in the function call.
  AMEDIA_ERROR_INVALID_OBJECT(-10003),

  /// At least one of the invalid parameters is used.
  AMEDIA_ERROR_INVALID_PARAMETER(-10004),

  /// The media object is not in the right state for the required operation.
  AMEDIA_ERROR_INVALID_OPERATION(-10005),

  /// Media stream ends while processing the requested operation.
  AMEDIA_ERROR_END_OF_STREAM(-10006),

  /// An Error occurred when the Media object is carrying IO operation.
  AMEDIA_ERROR_IO(-10007),

  /// The required operation would have to be blocked (on I/O or others), but
  /// blocking is not enabled.
  AMEDIA_ERROR_WOULD_BLOCK(-10008),
  AMEDIA_DRM_ERROR_BASE(-20000),
  AMEDIA_DRM_NOT_PROVISIONED(-20001),
  AMEDIA_DRM_RESOURCE_BUSY(-20002),
  AMEDIA_DRM_DEVICE_REVOKED(-20003),
  AMEDIA_DRM_SHORT_BUFFER(-20004),
  AMEDIA_DRM_SESSION_NOT_OPENED(-20005),
  AMEDIA_DRM_TAMPER_DETECTED(-20006),
  AMEDIA_DRM_VERIFY_FAILED(-20007),
  AMEDIA_DRM_NEED_KEY(-20008),
  AMEDIA_DRM_LICENSE_EXPIRED(-20009),
  AMEDIA_IMGREADER_ERROR_BASE(-30000),

  /// There are no more image buffers to read/write image data.
  AMEDIA_IMGREADER_NO_BUFFER_AVAILABLE(-30001),

  /// The AImage object has used up the allowed maximum image buffers.
  AMEDIA_IMGREADER_MAX_IMAGES_ACQUIRED(-30002),

  /// The required image buffer could not be locked to read.
  AMEDIA_IMGREADER_CANNOT_LOCK_IMAGE(-30003),

  /// The media data or buffer could not be unlocked.
  AMEDIA_IMGREADER_CANNOT_UNLOCK_IMAGE(-30004),

  /// The media/buffer needs to be locked to perform the required operation.
  AMEDIA_IMGREADER_IMAGE_NOT_LOCKED(-30005);

  /// The called media function failed with an unknown error.
  static const AMEDIA_ERROR_UNKNOWN = AMEDIA_ERROR_BASE;

  final int value;
  const media_status_t(this.value);

  static media_status_t fromValue(int value) => switch (value) {
    0 => AMEDIA_OK,
    1100 => AMEDIACODEC_ERROR_INSUFFICIENT_RESOURCE,
    1101 => AMEDIACODEC_ERROR_RECLAIMED,
    -10000 => AMEDIA_ERROR_BASE,
    -10001 => AMEDIA_ERROR_MALFORMED,
    -10002 => AMEDIA_ERROR_UNSUPPORTED,
    -10003 => AMEDIA_ERROR_INVALID_OBJECT,
    -10004 => AMEDIA_ERROR_INVALID_PARAMETER,
    -10005 => AMEDIA_ERROR_INVALID_OPERATION,
    -10006 => AMEDIA_ERROR_END_OF_STREAM,
    -10007 => AMEDIA_ERROR_IO,
    -10008 => AMEDIA_ERROR_WOULD_BLOCK,
    -20000 => AMEDIA_DRM_ERROR_BASE,
    -20001 => AMEDIA_DRM_NOT_PROVISIONED,
    -20002 => AMEDIA_DRM_RESOURCE_BUSY,
    -20003 => AMEDIA_DRM_DEVICE_REVOKED,
    -20004 => AMEDIA_DRM_SHORT_BUFFER,
    -20005 => AMEDIA_DRM_SESSION_NOT_OPENED,
    -20006 => AMEDIA_DRM_TAMPER_DETECTED,
    -20007 => AMEDIA_DRM_VERIFY_FAILED,
    -20008 => AMEDIA_DRM_NEED_KEY,
    -20009 => AMEDIA_DRM_LICENSE_EXPIRED,
    -30000 => AMEDIA_IMGREADER_ERROR_BASE,
    -30001 => AMEDIA_IMGREADER_NO_BUFFER_AVAILABLE,
    -30002 => AMEDIA_IMGREADER_MAX_IMAGES_ACQUIRED,
    -30003 => AMEDIA_IMGREADER_CANNOT_LOCK_IMAGE,
    -30004 => AMEDIA_IMGREADER_CANNOT_UNLOCK_IMAGE,
    -30005 => AMEDIA_IMGREADER_IMAGE_NOT_LOCKED,
    _ => throw ArgumentError('Unknown value for media_status_t: $value'),
  };

  @override
  String toString() {
    if (this == AMEDIA_ERROR_BASE)
      return "media_status_t.AMEDIA_ERROR_BASE, media_status_t.AMEDIA_ERROR_UNKNOWN";
    return super.toString();
  }
}

final class AMediaFormat extends ffi.Opaque {}

final class ANativeWindow extends ffi.Opaque {}

final class AMediaCodec extends ffi.Opaque {}

final class AMediaCodecBufferInfo extends ffi.Struct {
  @ffi.Int32()
  external int offset;

  @ffi.Int32()
  external int size;

  @ffi.Int64()
  external int presentationTimeUs;

  @ffi.Uint32()
  external int flags;
}

final class AMediaCrypto extends ffi.Opaque {}

enum cryptoinfo_mode_t {
  AMEDIACODECRYPTOINFO_MODE_CLEAR(0),
  AMEDIACODECRYPTOINFO_MODE_AES_CTR(1),
  AMEDIACODECRYPTOINFO_MODE_AES_WV(2),
  AMEDIACODECRYPTOINFO_MODE_AES_CBC(3);

  final int value;
  const cryptoinfo_mode_t(this.value);

  static cryptoinfo_mode_t fromValue(int value) => switch (value) {
    0 => AMEDIACODECRYPTOINFO_MODE_CLEAR,
    1 => AMEDIACODECRYPTOINFO_MODE_AES_CTR,
    2 => AMEDIACODECRYPTOINFO_MODE_AES_WV,
    3 => AMEDIACODECRYPTOINFO_MODE_AES_CBC,
    _ => throw ArgumentError('Unknown value for cryptoinfo_mode_t: $value'),
  };
}

const int AMEDIACODEC_BUFFER_FLAG_KEY_FRAME = 1;

const int AMEDIACODEC_BUFFER_FLAG_CODEC_CONFIG = 2;

const int AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM = 4;

const int AMEDIACODEC_BUFFER_FLAG_PARTIAL_FRAME = 8;

const int AMEDIACODEC_BUFFER_FLAG_MUXER_DATA = 16;

const int AMEDIACODEC_BUFFER_FLAG_DECODE_ONLY = 32;

const int AMEDIACODEC_CONFIGURE_FLAG_ENCODE = 1;

const int AMEDIACODEC_INFO_OUTPUT_BUFFERS_CHANGED = -3;

const int AMEDIACODEC_INFO_OUTPUT_FORMAT_CHANGED = -2;

const int AMEDIACODEC_INFO_TRY_AGAIN_LATER = -1;
