// GENERATED FILE — do not edit by hand. Regenerate with:
//   dart run ffigen --config ffigen.yaml

// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names, constant_identifier_names, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

// Opaque CoreFoundation CFString. ffigen 19 normally emits this as
// `objc.CFString` (toll-free bridge with NSString); we replace it with a
// local opaque struct to avoid pulling in package:objective_c for a type
// we only ever pass as a CFStringRef handle.
final class CFString extends ffi.Opaque {}

/// Hand-curated bindings for the macOS/iOS VideoToolbox H.264 helper.
/// Generated by ffigen from CoreFoundation/CoreVideo/CoreMedia/VideoToolbox
/// headers; the include lists in ffigen.yaml control what gets emitted.
///
class VtBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VtBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VtBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  late final ffi.Pointer<CFAllocatorRef> _kCFAllocatorDefault =
      _lookup<CFAllocatorRef>('kCFAllocatorDefault');

  CFAllocatorRef get kCFAllocatorDefault => _kCFAllocatorDefault.value;

  late final ffi.Pointer<CFAllocatorRef> _kCFAllocatorMalloc =
      _lookup<CFAllocatorRef>('kCFAllocatorMalloc');

  CFAllocatorRef get kCFAllocatorMalloc => _kCFAllocatorMalloc.value;

  CFTypeRef CFRetain(CFTypeRef cf) {
    return _CFRetain(cf);
  }

  late final _CFRetainPtr =
      _lookup<ffi.NativeFunction<CFTypeRef Function(CFTypeRef)>>('CFRetain');
  late final _CFRetain =
      _CFRetainPtr.asFunction<CFTypeRef Function(CFTypeRef)>();

  void CFRelease(CFTypeRef cf) {
    return _CFRelease(cf);
  }

  late final _CFReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(CFTypeRef)>>('CFRelease');
  late final _CFRelease = _CFReleasePtr.asFunction<void Function(CFTypeRef)>();

  int CFArrayGetCount(CFArrayRef theArray) {
    return _CFArrayGetCount(theArray);
  }

  late final _CFArrayGetCountPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(CFArrayRef)>>(
        'CFArrayGetCount',
      );
  late final _CFArrayGetCount =
      _CFArrayGetCountPtr.asFunction<int Function(CFArrayRef)>();

  ffi.Pointer<ffi.Void> CFArrayGetValueAtIndex(CFArrayRef theArray, int idx) {
    return _CFArrayGetValueAtIndex(theArray, idx);
  }

  late final _CFArrayGetValueAtIndexPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(CFArrayRef, ffi.Long)>
      >('CFArrayGetValueAtIndex');
  late final _CFArrayGetValueAtIndex =
      _CFArrayGetValueAtIndexPtr.asFunction<
        ffi.Pointer<ffi.Void> Function(CFArrayRef, int)
      >();

  late final ffi.Pointer<CFDictionaryKeyCallBacks>
  _kCFTypeDictionaryKeyCallBacks = _lookup<CFDictionaryKeyCallBacks>(
    'kCFTypeDictionaryKeyCallBacks',
  );

  CFDictionaryKeyCallBacks get kCFTypeDictionaryKeyCallBacks =>
      _kCFTypeDictionaryKeyCallBacks.ref;

  late final ffi.Pointer<CFDictionaryValueCallBacks>
  _kCFTypeDictionaryValueCallBacks = _lookup<CFDictionaryValueCallBacks>(
    'kCFTypeDictionaryValueCallBacks',
  );

  CFDictionaryValueCallBacks get kCFTypeDictionaryValueCallBacks =>
      _kCFTypeDictionaryValueCallBacks.ref;

  CFDictionaryRef CFDictionaryCreate(
    CFAllocatorRef allocator,
    ffi.Pointer<ffi.Pointer<ffi.Void>> keys,
    ffi.Pointer<ffi.Pointer<ffi.Void>> values,
    int numValues,
    ffi.Pointer<CFDictionaryKeyCallBacks> keyCallBacks,
    ffi.Pointer<CFDictionaryValueCallBacks> valueCallBacks,
  ) {
    return _CFDictionaryCreate(
      allocator,
      keys,
      values,
      numValues,
      keyCallBacks,
      valueCallBacks,
    );
  }

  late final _CFDictionaryCreatePtr =
      _lookup<
        ffi.NativeFunction<
          CFDictionaryRef Function(
            CFAllocatorRef,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Long,
            ffi.Pointer<CFDictionaryKeyCallBacks>,
            ffi.Pointer<CFDictionaryValueCallBacks>,
          )
        >
      >('CFDictionaryCreate');
  late final _CFDictionaryCreate =
      _CFDictionaryCreatePtr.asFunction<
        CFDictionaryRef Function(
          CFAllocatorRef,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
          int,
          ffi.Pointer<CFDictionaryKeyCallBacks>,
          ffi.Pointer<CFDictionaryValueCallBacks>,
        )
      >();

  int CFDictionaryContainsKey(
    CFDictionaryRef theDict,
    ffi.Pointer<ffi.Void> key,
  ) {
    return _CFDictionaryContainsKey(theDict, key);
  }

  late final _CFDictionaryContainsKeyPtr =
      _lookup<
        ffi.NativeFunction<
          Boolean Function(CFDictionaryRef, ffi.Pointer<ffi.Void>)
        >
      >('CFDictionaryContainsKey');
  late final _CFDictionaryContainsKey =
      _CFDictionaryContainsKeyPtr.asFunction<
        int Function(CFDictionaryRef, ffi.Pointer<ffi.Void>)
      >();

  late final ffi.Pointer<CFBooleanRef> _kCFBooleanTrue = _lookup<CFBooleanRef>(
    'kCFBooleanTrue',
  );

  CFBooleanRef get kCFBooleanTrue => _kCFBooleanTrue.value;

  CFNumberRef CFNumberCreate(
    CFAllocatorRef allocator,
    int theType,
    ffi.Pointer<ffi.Void> valuePtr,
  ) {
    return _CFNumberCreate(allocator, theType, valuePtr);
  }

  late final _CFNumberCreatePtr =
      _lookup<
        ffi.NativeFunction<
          CFNumberRef Function(CFAllocatorRef, ffi.Long, ffi.Pointer<ffi.Void>)
        >
      >('CFNumberCreate');
  late final _CFNumberCreate =
      _CFNumberCreatePtr.asFunction<
        CFNumberRef Function(CFAllocatorRef, int, ffi.Pointer<ffi.Void>)
      >();

  late final ffi.Pointer<CFStringRef> _kCVPixelBufferPixelFormatTypeKey =
      _lookup<CFStringRef>('kCVPixelBufferPixelFormatTypeKey');

  CFStringRef get kCVPixelBufferPixelFormatTypeKey =>
      _kCVPixelBufferPixelFormatTypeKey.value;

  late final ffi.Pointer<CFStringRef> _kCVPixelBufferIOSurfacePropertiesKey =
      _lookup<CFStringRef>('kCVPixelBufferIOSurfacePropertiesKey');

  CFStringRef get kCVPixelBufferIOSurfacePropertiesKey =>
      _kCVPixelBufferIOSurfacePropertiesKey.value;

  void CVPixelBufferRelease(CVPixelBufferRef texture) {
    return _CVPixelBufferRelease(texture);
  }

  late final _CVPixelBufferReleasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(CVPixelBufferRef)>>(
        'CVPixelBufferRelease',
      );
  late final _CVPixelBufferRelease =
      _CVPixelBufferReleasePtr.asFunction<void Function(CVPixelBufferRef)>();

  int CVPixelBufferCreate(
    CFAllocatorRef allocator,
    int width,
    int height,
    int pixelFormatType,
    CFDictionaryRef pixelBufferAttributes,
    ffi.Pointer<CVPixelBufferRef> pixelBufferOut,
  ) {
    return _CVPixelBufferCreate(
      allocator,
      width,
      height,
      pixelFormatType,
      pixelBufferAttributes,
      pixelBufferOut,
    );
  }

  late final _CVPixelBufferCreatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            CFAllocatorRef,
            ffi.Size,
            ffi.Size,
            OSType,
            CFDictionaryRef,
            ffi.Pointer<CVPixelBufferRef>,
          )
        >
      >('CVPixelBufferCreate');
  late final _CVPixelBufferCreate =
      _CVPixelBufferCreatePtr.asFunction<
        int Function(
          CFAllocatorRef,
          int,
          int,
          int,
          CFDictionaryRef,
          ffi.Pointer<CVPixelBufferRef>,
        )
      >();

  int CVPixelBufferLockBaseAddress(
    CVPixelBufferRef pixelBuffer,
    int lockFlags,
  ) {
    return _CVPixelBufferLockBaseAddress(pixelBuffer, lockFlags);
  }

  late final _CVPixelBufferLockBaseAddressPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(CVPixelBufferRef, ffi.Uint64)>
      >('CVPixelBufferLockBaseAddress');
  late final _CVPixelBufferLockBaseAddress =
      _CVPixelBufferLockBaseAddressPtr.asFunction<
        int Function(CVPixelBufferRef, int)
      >();

  int CVPixelBufferUnlockBaseAddress(
    CVPixelBufferRef pixelBuffer,
    int unlockFlags,
  ) {
    return _CVPixelBufferUnlockBaseAddress(pixelBuffer, unlockFlags);
  }

  late final _CVPixelBufferUnlockBaseAddressPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(CVPixelBufferRef, ffi.Uint64)>
      >('CVPixelBufferUnlockBaseAddress');
  late final _CVPixelBufferUnlockBaseAddress =
      _CVPixelBufferUnlockBaseAddressPtr.asFunction<
        int Function(CVPixelBufferRef, int)
      >();

  int CVPixelBufferGetWidth(CVPixelBufferRef pixelBuffer) {
    return _CVPixelBufferGetWidth(pixelBuffer);
  }

  late final _CVPixelBufferGetWidthPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(CVPixelBufferRef)>>(
        'CVPixelBufferGetWidth',
      );
  late final _CVPixelBufferGetWidth =
      _CVPixelBufferGetWidthPtr.asFunction<int Function(CVPixelBufferRef)>();

  int CVPixelBufferGetHeight(CVPixelBufferRef pixelBuffer) {
    return _CVPixelBufferGetHeight(pixelBuffer);
  }

  late final _CVPixelBufferGetHeightPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(CVPixelBufferRef)>>(
        'CVPixelBufferGetHeight',
      );
  late final _CVPixelBufferGetHeight =
      _CVPixelBufferGetHeightPtr.asFunction<int Function(CVPixelBufferRef)>();

  int CVPixelBufferGetPixelFormatType(CVPixelBufferRef pixelBuffer) {
    return _CVPixelBufferGetPixelFormatType(pixelBuffer);
  }

  late final _CVPixelBufferGetPixelFormatTypePtr =
      _lookup<ffi.NativeFunction<OSType Function(CVPixelBufferRef)>>(
        'CVPixelBufferGetPixelFormatType',
      );
  late final _CVPixelBufferGetPixelFormatType =
      _CVPixelBufferGetPixelFormatTypePtr.asFunction<
        int Function(CVPixelBufferRef)
      >();

  ffi.Pointer<ffi.Void> CVPixelBufferGetBaseAddressOfPlane(
    CVPixelBufferRef pixelBuffer,
    int planeIndex,
  ) {
    return _CVPixelBufferGetBaseAddressOfPlane(pixelBuffer, planeIndex);
  }

  late final _CVPixelBufferGetBaseAddressOfPlanePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(CVPixelBufferRef, ffi.Size)
        >
      >('CVPixelBufferGetBaseAddressOfPlane');
  late final _CVPixelBufferGetBaseAddressOfPlane =
      _CVPixelBufferGetBaseAddressOfPlanePtr.asFunction<
        ffi.Pointer<ffi.Void> Function(CVPixelBufferRef, int)
      >();

  int CVPixelBufferGetBytesPerRowOfPlane(
    CVPixelBufferRef pixelBuffer,
    int planeIndex,
  ) {
    return _CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, planeIndex);
  }

  late final _CVPixelBufferGetBytesPerRowOfPlanePtr =
      _lookup<
        ffi.NativeFunction<ffi.Size Function(CVPixelBufferRef, ffi.Size)>
      >('CVPixelBufferGetBytesPerRowOfPlane');
  late final _CVPixelBufferGetBytesPerRowOfPlane =
      _CVPixelBufferGetBytesPerRowOfPlanePtr.asFunction<
        int Function(CVPixelBufferRef, int)
      >();

  late final ffi.Pointer<CMTime> _kCMTimeInvalid = _lookup<CMTime>(
    'kCMTimeInvalid',
  );

  CMTime get kCMTimeInvalid => _kCMTimeInvalid.ref;

  CMTime CMTimeMake(int value, int timescale) {
    return _CMTimeMake(value, timescale);
  }

  late final _CMTimeMakePtr =
      _lookup<ffi.NativeFunction<CMTime Function(ffi.Int64, ffi.Int32)>>(
        'CMTimeMake',
      );
  late final _CMTimeMake =
      _CMTimeMakePtr.asFunction<CMTime Function(int, int)>();

  int CMVideoFormatDescriptionCreateFromH264ParameterSets(
    CFAllocatorRef allocator,
    int parameterSetCount,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> parameterSetPointers,
    ffi.Pointer<ffi.Size> parameterSetSizes,
    int NALUnitHeaderLength,
    ffi.Pointer<CMFormatDescriptionRef> formatDescriptionOut,
  ) {
    return _CMVideoFormatDescriptionCreateFromH264ParameterSets(
      allocator,
      parameterSetCount,
      parameterSetPointers,
      parameterSetSizes,
      NALUnitHeaderLength,
      formatDescriptionOut,
    );
  }

  late final _CMVideoFormatDescriptionCreateFromH264ParameterSetsPtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CFAllocatorRef,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
            ffi.Int,
            ffi.Pointer<CMFormatDescriptionRef>,
          )
        >
      >('CMVideoFormatDescriptionCreateFromH264ParameterSets');
  late final _CMVideoFormatDescriptionCreateFromH264ParameterSets =
      _CMVideoFormatDescriptionCreateFromH264ParameterSetsPtr.asFunction<
        int Function(
          CFAllocatorRef,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
          int,
          ffi.Pointer<CMFormatDescriptionRef>,
        )
      >();

  int CMVideoFormatDescriptionGetH264ParameterSetAtIndex(
    CMFormatDescriptionRef videoDesc,
    int parameterSetIndex,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> parameterSetPointerOut,
    ffi.Pointer<ffi.Size> parameterSetSizeOut,
    ffi.Pointer<ffi.Size> parameterSetCountOut,
    ffi.Pointer<ffi.Int> NALUnitHeaderLengthOut,
  ) {
    return _CMVideoFormatDescriptionGetH264ParameterSetAtIndex(
      videoDesc,
      parameterSetIndex,
      parameterSetPointerOut,
      parameterSetSizeOut,
      parameterSetCountOut,
      NALUnitHeaderLengthOut,
    );
  }

  late final _CMVideoFormatDescriptionGetH264ParameterSetAtIndexPtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CMFormatDescriptionRef,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('CMVideoFormatDescriptionGetH264ParameterSetAtIndex');
  late final _CMVideoFormatDescriptionGetH264ParameterSetAtIndex =
      _CMVideoFormatDescriptionGetH264ParameterSetAtIndexPtr.asFunction<
        int Function(
          CMFormatDescriptionRef,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  CMVideoDimensions CMVideoFormatDescriptionGetDimensions(
    CMVideoFormatDescriptionRef videoDesc,
  ) {
    return _CMVideoFormatDescriptionGetDimensions(videoDesc);
  }

  late final _CMVideoFormatDescriptionGetDimensionsPtr =
      _lookup<
        ffi.NativeFunction<
          CMVideoDimensions Function(CMVideoFormatDescriptionRef)
        >
      >('CMVideoFormatDescriptionGetDimensions');
  late final _CMVideoFormatDescriptionGetDimensions =
      _CMVideoFormatDescriptionGetDimensionsPtr.asFunction<
        CMVideoDimensions Function(CMVideoFormatDescriptionRef)
      >();

  int CMBlockBufferCreateWithMemoryBlock(
    CFAllocatorRef structureAllocator,
    ffi.Pointer<ffi.Void> memoryBlock,
    int blockLength,
    CFAllocatorRef blockAllocator,
    ffi.Pointer<CMBlockBufferCustomBlockSource> customBlockSource,
    int offsetToData,
    int dataLength,
    int flags,
    ffi.Pointer<CMBlockBufferRef> blockBufferOut,
  ) {
    return _CMBlockBufferCreateWithMemoryBlock(
      structureAllocator,
      memoryBlock,
      blockLength,
      blockAllocator,
      customBlockSource,
      offsetToData,
      dataLength,
      flags,
      blockBufferOut,
    );
  }

  late final _CMBlockBufferCreateWithMemoryBlockPtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CFAllocatorRef,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            CFAllocatorRef,
            ffi.Pointer<CMBlockBufferCustomBlockSource>,
            ffi.Size,
            ffi.Size,
            ffi.Uint32,
            ffi.Pointer<CMBlockBufferRef>,
          )
        >
      >('CMBlockBufferCreateWithMemoryBlock');
  late final _CMBlockBufferCreateWithMemoryBlock =
      _CMBlockBufferCreateWithMemoryBlockPtr.asFunction<
        int Function(
          CFAllocatorRef,
          ffi.Pointer<ffi.Void>,
          int,
          CFAllocatorRef,
          ffi.Pointer<CMBlockBufferCustomBlockSource>,
          int,
          int,
          int,
          ffi.Pointer<CMBlockBufferRef>,
        )
      >();

  int CMBlockBufferGetDataPointer(
    CMBlockBufferRef theBuffer,
    int offset,
    ffi.Pointer<ffi.Size> lengthAtOffsetOut,
    ffi.Pointer<ffi.Size> totalLengthOut,
    ffi.Pointer<ffi.Pointer<ffi.Char>> dataPointerOut,
  ) {
    return _CMBlockBufferGetDataPointer(
      theBuffer,
      offset,
      lengthAtOffsetOut,
      totalLengthOut,
      dataPointerOut,
    );
  }

  late final _CMBlockBufferGetDataPointerPtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CMBlockBufferRef,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('CMBlockBufferGetDataPointer');
  late final _CMBlockBufferGetDataPointer =
      _CMBlockBufferGetDataPointerPtr.asFunction<
        int Function(
          CMBlockBufferRef,
          int,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int CMSampleBufferCreate(
    CFAllocatorRef allocator,
    CMBlockBufferRef dataBuffer,
    int dataReady,
    ffi.Pointer<
      ffi.NativeFunction<
        OSStatus Function(
          CMSampleBufferRef sbuf,
          ffi.Pointer<ffi.Void> makeDataReadyRefcon,
        )
      >
    >
    makeDataReadyCallback,
    ffi.Pointer<ffi.Void> makeDataReadyRefcon,
    CMFormatDescriptionRef formatDescription,
    int numSamples,
    int numSampleTimingEntries,
    ffi.Pointer<CMSampleTimingInfo> sampleTimingArray,
    int numSampleSizeEntries,
    ffi.Pointer<ffi.Size> sampleSizeArray,
    ffi.Pointer<CMSampleBufferRef> sampleBufferOut,
  ) {
    return _CMSampleBufferCreate(
      allocator,
      dataBuffer,
      dataReady,
      makeDataReadyCallback,
      makeDataReadyRefcon,
      formatDescription,
      numSamples,
      numSampleTimingEntries,
      sampleTimingArray,
      numSampleSizeEntries,
      sampleSizeArray,
      sampleBufferOut,
    );
  }

  late final _CMSampleBufferCreatePtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CFAllocatorRef,
            CMBlockBufferRef,
            Boolean,
            ffi.Pointer<
              ffi.NativeFunction<
                OSStatus Function(
                  CMSampleBufferRef sbuf,
                  ffi.Pointer<ffi.Void> makeDataReadyRefcon,
                )
              >
            >,
            ffi.Pointer<ffi.Void>,
            CMFormatDescriptionRef,
            ffi.Long,
            ffi.Long,
            ffi.Pointer<CMSampleTimingInfo>,
            ffi.Long,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<CMSampleBufferRef>,
          )
        >
      >('CMSampleBufferCreate');
  late final _CMSampleBufferCreate =
      _CMSampleBufferCreatePtr.asFunction<
        int Function(
          CFAllocatorRef,
          CMBlockBufferRef,
          int,
          ffi.Pointer<
            ffi.NativeFunction<
              OSStatus Function(
                CMSampleBufferRef sbuf,
                ffi.Pointer<ffi.Void> makeDataReadyRefcon,
              )
            >
          >,
          ffi.Pointer<ffi.Void>,
          CMFormatDescriptionRef,
          int,
          int,
          ffi.Pointer<CMSampleTimingInfo>,
          int,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<CMSampleBufferRef>,
        )
      >();

  CMBlockBufferRef CMSampleBufferGetDataBuffer(CMSampleBufferRef sbuf) {
    return _CMSampleBufferGetDataBuffer(sbuf);
  }

  late final _CMSampleBufferGetDataBufferPtr =
      _lookup<ffi.NativeFunction<CMBlockBufferRef Function(CMSampleBufferRef)>>(
        'CMSampleBufferGetDataBuffer',
      );
  late final _CMSampleBufferGetDataBuffer =
      _CMSampleBufferGetDataBufferPtr.asFunction<
        CMBlockBufferRef Function(CMSampleBufferRef)
      >();

  CMFormatDescriptionRef CMSampleBufferGetFormatDescription(
    CMSampleBufferRef sbuf,
  ) {
    return _CMSampleBufferGetFormatDescription(sbuf);
  }

  late final _CMSampleBufferGetFormatDescriptionPtr =
      _lookup<
        ffi.NativeFunction<CMFormatDescriptionRef Function(CMSampleBufferRef)>
      >('CMSampleBufferGetFormatDescription');
  late final _CMSampleBufferGetFormatDescription =
      _CMSampleBufferGetFormatDescriptionPtr.asFunction<
        CMFormatDescriptionRef Function(CMSampleBufferRef)
      >();

  CFArrayRef CMSampleBufferGetSampleAttachmentsArray(
    CMSampleBufferRef sbuf,
    int createIfNecessary,
  ) {
    return _CMSampleBufferGetSampleAttachmentsArray(sbuf, createIfNecessary);
  }

  late final _CMSampleBufferGetSampleAttachmentsArrayPtr =
      _lookup<
        ffi.NativeFunction<CFArrayRef Function(CMSampleBufferRef, Boolean)>
      >('CMSampleBufferGetSampleAttachmentsArray');
  late final _CMSampleBufferGetSampleAttachmentsArray =
      _CMSampleBufferGetSampleAttachmentsArrayPtr.asFunction<
        CFArrayRef Function(CMSampleBufferRef, int)
      >();

  late final ffi.Pointer<CFStringRef> _kCMSampleAttachmentKey_NotSync =
      _lookup<CFStringRef>('kCMSampleAttachmentKey_NotSync');

  CFStringRef get kCMSampleAttachmentKey_NotSync =>
      _kCMSampleAttachmentKey_NotSync.value;

  set kCMSampleAttachmentKey_NotSync(CFStringRef value) =>
      _kCMSampleAttachmentKey_NotSync.value = value;

  late final ffi.Pointer<CFStringRef>
  _kVTCompressionPropertyKey_MaxKeyFrameInterval = _lookup<CFStringRef>(
    'kVTCompressionPropertyKey_MaxKeyFrameInterval',
  );

  CFStringRef get kVTCompressionPropertyKey_MaxKeyFrameInterval =>
      _kVTCompressionPropertyKey_MaxKeyFrameInterval.value;

  set kVTCompressionPropertyKey_MaxKeyFrameInterval(CFStringRef value) =>
      _kVTCompressionPropertyKey_MaxKeyFrameInterval.value = value;

  late final ffi.Pointer<CFStringRef>
  _kVTCompressionPropertyKey_AllowFrameReordering = _lookup<CFStringRef>(
    'kVTCompressionPropertyKey_AllowFrameReordering',
  );

  CFStringRef get kVTCompressionPropertyKey_AllowFrameReordering =>
      _kVTCompressionPropertyKey_AllowFrameReordering.value;

  set kVTCompressionPropertyKey_AllowFrameReordering(CFStringRef value) =>
      _kVTCompressionPropertyKey_AllowFrameReordering.value = value;

  late final ffi.Pointer<CFStringRef>
  _kVTCompressionPropertyKey_AverageBitRate = _lookup<CFStringRef>(
    'kVTCompressionPropertyKey_AverageBitRate',
  );

  CFStringRef get kVTCompressionPropertyKey_AverageBitRate =>
      _kVTCompressionPropertyKey_AverageBitRate.value;

  set kVTCompressionPropertyKey_AverageBitRate(CFStringRef value) =>
      _kVTCompressionPropertyKey_AverageBitRate.value = value;

  late final ffi.Pointer<CFStringRef> _kVTCompressionPropertyKey_ProfileLevel =
      _lookup<CFStringRef>('kVTCompressionPropertyKey_ProfileLevel');

  CFStringRef get kVTCompressionPropertyKey_ProfileLevel =>
      _kVTCompressionPropertyKey_ProfileLevel.value;

  set kVTCompressionPropertyKey_ProfileLevel(CFStringRef value) =>
      _kVTCompressionPropertyKey_ProfileLevel.value = value;

  late final ffi.Pointer<CFStringRef> _kVTProfileLevel_H264_Baseline_AutoLevel =
      _lookup<CFStringRef>('kVTProfileLevel_H264_Baseline_AutoLevel');

  CFStringRef get kVTProfileLevel_H264_Baseline_AutoLevel =>
      _kVTProfileLevel_H264_Baseline_AutoLevel.value;

  set kVTProfileLevel_H264_Baseline_AutoLevel(CFStringRef value) =>
      _kVTProfileLevel_H264_Baseline_AutoLevel.value = value;

  late final ffi.Pointer<CFStringRef> _kVTCompressionPropertyKey_RealTime =
      _lookup<CFStringRef>('kVTCompressionPropertyKey_RealTime');

  CFStringRef get kVTCompressionPropertyKey_RealTime =>
      _kVTCompressionPropertyKey_RealTime.value;

  set kVTCompressionPropertyKey_RealTime(CFStringRef value) =>
      _kVTCompressionPropertyKey_RealTime.value = value;

  late final ffi.Pointer<CFStringRef>
  _kVTCompressionPropertyKey_ExpectedFrameRate = _lookup<CFStringRef>(
    'kVTCompressionPropertyKey_ExpectedFrameRate',
  );

  CFStringRef get kVTCompressionPropertyKey_ExpectedFrameRate =>
      _kVTCompressionPropertyKey_ExpectedFrameRate.value;

  set kVTCompressionPropertyKey_ExpectedFrameRate(CFStringRef value) =>
      _kVTCompressionPropertyKey_ExpectedFrameRate.value = value;

  late final ffi.Pointer<CFStringRef> _kVTEncodeFrameOptionKey_ForceKeyFrame =
      _lookup<CFStringRef>('kVTEncodeFrameOptionKey_ForceKeyFrame');

  CFStringRef get kVTEncodeFrameOptionKey_ForceKeyFrame =>
      _kVTEncodeFrameOptionKey_ForceKeyFrame.value;

  set kVTEncodeFrameOptionKey_ForceKeyFrame(CFStringRef value) =>
      _kVTEncodeFrameOptionKey_ForceKeyFrame.value = value;

  int VTSessionSetProperty(
    CFTypeRef session,
    CFStringRef propertyKey,
    CFTypeRef propertyValue,
  ) {
    return _VTSessionSetProperty(session, propertyKey, propertyValue);
  }

  late final _VTSessionSetPropertyPtr =
      _lookup<
        ffi.NativeFunction<OSStatus Function(CFTypeRef, CFStringRef, CFTypeRef)>
      >('VTSessionSetProperty');
  late final _VTSessionSetProperty =
      _VTSessionSetPropertyPtr.asFunction<
        int Function(CFTypeRef, CFStringRef, CFTypeRef)
      >();

  int VTCompressionSessionCreate(
    CFAllocatorRef allocator,
    int width,
    int height,
    int codecType,
    CFDictionaryRef encoderSpecification,
    CFDictionaryRef sourceImageBufferAttributes,
    CFAllocatorRef compressedDataAllocator,
    VTCompressionOutputCallback outputCallback,
    ffi.Pointer<ffi.Void> outputCallbackRefCon,
    ffi.Pointer<VTCompressionSessionRef> compressionSessionOut,
  ) {
    return _VTCompressionSessionCreate(
      allocator,
      width,
      height,
      codecType,
      encoderSpecification,
      sourceImageBufferAttributes,
      compressedDataAllocator,
      outputCallback,
      outputCallbackRefCon,
      compressionSessionOut,
    );
  }

  late final _VTCompressionSessionCreatePtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CFAllocatorRef,
            ffi.Int32,
            ffi.Int32,
            ffi.UnsignedInt,
            CFDictionaryRef,
            CFDictionaryRef,
            CFAllocatorRef,
            VTCompressionOutputCallback,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<VTCompressionSessionRef>,
          )
        >
      >('VTCompressionSessionCreate');
  late final _VTCompressionSessionCreate =
      _VTCompressionSessionCreatePtr.asFunction<
        int Function(
          CFAllocatorRef,
          int,
          int,
          int,
          CFDictionaryRef,
          CFDictionaryRef,
          CFAllocatorRef,
          VTCompressionOutputCallback,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<VTCompressionSessionRef>,
        )
      >();

  void VTCompressionSessionInvalidate(VTCompressionSessionRef session) {
    return _VTCompressionSessionInvalidate(session);
  }

  late final _VTCompressionSessionInvalidatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VTCompressionSessionRef)>>(
        'VTCompressionSessionInvalidate',
      );
  late final _VTCompressionSessionInvalidate =
      _VTCompressionSessionInvalidatePtr.asFunction<
        void Function(VTCompressionSessionRef)
      >();

  int VTCompressionSessionPrepareToEncodeFrames(
    VTCompressionSessionRef session,
  ) {
    return _VTCompressionSessionPrepareToEncodeFrames(session);
  }

  late final _VTCompressionSessionPrepareToEncodeFramesPtr =
      _lookup<ffi.NativeFunction<OSStatus Function(VTCompressionSessionRef)>>(
        'VTCompressionSessionPrepareToEncodeFrames',
      );
  late final _VTCompressionSessionPrepareToEncodeFrames =
      _VTCompressionSessionPrepareToEncodeFramesPtr.asFunction<
        int Function(VTCompressionSessionRef)
      >();

  int VTCompressionSessionEncodeFrame(
    VTCompressionSessionRef session,
    CVImageBufferRef imageBuffer,
    CMTime presentationTimeStamp,
    CMTime duration,
    CFDictionaryRef frameProperties,
    ffi.Pointer<ffi.Void> sourceFrameRefcon,
    ffi.Pointer<ffi.UnsignedInt> infoFlagsOut,
  ) {
    return _VTCompressionSessionEncodeFrame(
      session,
      imageBuffer,
      presentationTimeStamp,
      duration,
      frameProperties,
      sourceFrameRefcon,
      infoFlagsOut,
    );
  }

  late final _VTCompressionSessionEncodeFramePtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            VTCompressionSessionRef,
            CVImageBufferRef,
            CMTime,
            CMTime,
            CFDictionaryRef,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.UnsignedInt>,
          )
        >
      >('VTCompressionSessionEncodeFrame');
  late final _VTCompressionSessionEncodeFrame =
      _VTCompressionSessionEncodeFramePtr.asFunction<
        int Function(
          VTCompressionSessionRef,
          CVImageBufferRef,
          CMTime,
          CMTime,
          CFDictionaryRef,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.UnsignedInt>,
        )
      >();

  int VTCompressionSessionCompleteFrames(
    VTCompressionSessionRef session,
    CMTime completeUntilPresentationTimeStamp,
  ) {
    return _VTCompressionSessionCompleteFrames(
      session,
      completeUntilPresentationTimeStamp,
    );
  }

  late final _VTCompressionSessionCompleteFramesPtr =
      _lookup<
        ffi.NativeFunction<OSStatus Function(VTCompressionSessionRef, CMTime)>
      >('VTCompressionSessionCompleteFrames');
  late final _VTCompressionSessionCompleteFrames =
      _VTCompressionSessionCompleteFramesPtr.asFunction<
        int Function(VTCompressionSessionRef, CMTime)
      >();

  int VTDecompressionSessionCreate(
    CFAllocatorRef allocator,
    CMVideoFormatDescriptionRef videoFormatDescription,
    CFDictionaryRef videoDecoderSpecification,
    CFDictionaryRef destinationImageBufferAttributes,
    ffi.Pointer<VTDecompressionOutputCallbackRecord> outputCallback,
    ffi.Pointer<VTDecompressionSessionRef> decompressionSessionOut,
  ) {
    return _VTDecompressionSessionCreate(
      allocator,
      videoFormatDescription,
      videoDecoderSpecification,
      destinationImageBufferAttributes,
      outputCallback,
      decompressionSessionOut,
    );
  }

  late final _VTDecompressionSessionCreatePtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            CFAllocatorRef,
            CMVideoFormatDescriptionRef,
            CFDictionaryRef,
            CFDictionaryRef,
            ffi.Pointer<VTDecompressionOutputCallbackRecord>,
            ffi.Pointer<VTDecompressionSessionRef>,
          )
        >
      >('VTDecompressionSessionCreate');
  late final _VTDecompressionSessionCreate =
      _VTDecompressionSessionCreatePtr.asFunction<
        int Function(
          CFAllocatorRef,
          CMVideoFormatDescriptionRef,
          CFDictionaryRef,
          CFDictionaryRef,
          ffi.Pointer<VTDecompressionOutputCallbackRecord>,
          ffi.Pointer<VTDecompressionSessionRef>,
        )
      >();

  void VTDecompressionSessionInvalidate(VTDecompressionSessionRef session) {
    return _VTDecompressionSessionInvalidate(session);
  }

  late final _VTDecompressionSessionInvalidatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(VTDecompressionSessionRef)>>(
        'VTDecompressionSessionInvalidate',
      );
  late final _VTDecompressionSessionInvalidate =
      _VTDecompressionSessionInvalidatePtr.asFunction<
        void Function(VTDecompressionSessionRef)
      >();

  int VTDecompressionSessionDecodeFrame(
    VTDecompressionSessionRef session,
    CMSampleBufferRef sampleBuffer,
    int decodeFlags,
    ffi.Pointer<ffi.Void> sourceFrameRefCon,
    ffi.Pointer<ffi.UnsignedInt> infoFlagsOut,
  ) {
    return _VTDecompressionSessionDecodeFrame(
      session,
      sampleBuffer,
      decodeFlags,
      sourceFrameRefCon,
      infoFlagsOut,
    );
  }

  late final _VTDecompressionSessionDecodeFramePtr =
      _lookup<
        ffi.NativeFunction<
          OSStatus Function(
            VTDecompressionSessionRef,
            CMSampleBufferRef,
            ffi.Uint32,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.UnsignedInt>,
          )
        >
      >('VTDecompressionSessionDecodeFrame');
  late final _VTDecompressionSessionDecodeFrame =
      _VTDecompressionSessionDecodeFramePtr.asFunction<
        int Function(
          VTDecompressionSessionRef,
          CMSampleBufferRef,
          int,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.UnsignedInt>,
        )
      >();

  int VTDecompressionSessionWaitForAsynchronousFrames(
    VTDecompressionSessionRef session,
  ) {
    return _VTDecompressionSessionWaitForAsynchronousFrames(session);
  }

  late final _VTDecompressionSessionWaitForAsynchronousFramesPtr =
      _lookup<ffi.NativeFunction<OSStatus Function(VTDecompressionSessionRef)>>(
        'VTDecompressionSessionWaitForAsynchronousFrames',
      );
  late final _VTDecompressionSessionWaitForAsynchronousFrames =
      _VTDecompressionSessionWaitForAsynchronousFramesPtr.asFunction<
        int Function(VTDecompressionSessionRef)
      >();
}

typedef CFTypeRef = ffi.Pointer<ffi.Void>;
typedef CFStringRef = ffi.Pointer<CFString>;

final class CFRange extends ffi.Struct {
  @ffi.Long()
  external int location;

  @ffi.Long()
  external int length;
}

final class CFAllocator extends ffi.Opaque {}

typedef CFAllocatorRef = ffi.Pointer<CFAllocator>;

final class CFArray extends ffi.Opaque {}

typedef CFArrayRef = ffi.Pointer<CFArray>;
typedef Boolean = ffi.UnsignedChar;
typedef DartBoolean = int;

final class CFDictionaryKeyCallBacks extends ffi.Struct {
  @ffi.Long()
  external int version;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        CFAllocatorRef allocator,
        ffi.Pointer<ffi.Void> value,
      )
    >
  >
  retain;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(CFAllocatorRef allocator, ffi.Pointer<ffi.Void> value)
    >
  >
  release;

  external ffi.Pointer<
    ffi.NativeFunction<CFStringRef Function(ffi.Pointer<ffi.Void> value)>
  >
  copyDescription;

  external ffi.Pointer<
    ffi.NativeFunction<
      Boolean Function(
        ffi.Pointer<ffi.Void> value1,
        ffi.Pointer<ffi.Void> value2,
      )
    >
  >
  equal;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void> value)>
  >
  hash;
}

final class CFDictionaryValueCallBacks extends ffi.Struct {
  @ffi.Long()
  external int version;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        CFAllocatorRef allocator,
        ffi.Pointer<ffi.Void> value,
      )
    >
  >
  retain;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(CFAllocatorRef allocator, ffi.Pointer<ffi.Void> value)
    >
  >
  release;

  external ffi.Pointer<
    ffi.NativeFunction<CFStringRef Function(ffi.Pointer<ffi.Void> value)>
  >
  copyDescription;

  external ffi.Pointer<
    ffi.NativeFunction<
      Boolean Function(
        ffi.Pointer<ffi.Void> value1,
        ffi.Pointer<ffi.Void> value2,
      )
    >
  >
  equal;
}

final class CFDictionary extends ffi.Opaque {}

typedef CFDictionaryRef = ffi.Pointer<CFDictionary>;

final class CFBoolean extends ffi.Opaque {}

typedef CFBooleanRef = ffi.Pointer<CFBoolean>;

final class CFNumber extends ffi.Opaque {}

typedef CFNumberRef = ffi.Pointer<CFNumber>;

final class CVBuffer extends ffi.Opaque {}

typedef CVImageBufferRef = ffi.Pointer<CVBuffer>;
typedef CVPixelBufferRef = CVImageBufferRef;
typedef OSType = ffi.UnsignedInt;

@ffi.Packed(4)
final class CMTime extends ffi.Struct {
  @ffi.Int64()
  external int value;

  @ffi.Int32()
  external int timescale;

  @ffi.Uint32()
  external int flags;

  @ffi.Int64()
  external int epoch;
}

final class opaqueCMFormatDescription extends ffi.Opaque {}

typedef CMFormatDescriptionRef = ffi.Pointer<opaqueCMFormatDescription>;
typedef CMVideoFormatDescriptionRef = CMFormatDescriptionRef;

final class CMVideoDimensions extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;
}

typedef OSStatus = ffi.Int;

final class OpaqueCMBlockBuffer extends ffi.Opaque {}

typedef CMBlockBufferRef = ffi.Pointer<OpaqueCMBlockBuffer>;

@ffi.Packed(4)
final class CMBlockBufferCustomBlockSource extends ffi.Struct {
  @ffi.Uint32()
  external int version;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<ffi.Void> refcon,
        ffi.Size sizeInBytes,
      )
    >
  >
  AllocateBlock;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> refcon,
        ffi.Pointer<ffi.Void> doomedMemoryBlock,
        ffi.Size sizeInBytes,
      )
    >
  >
  FreeBlock;

  external ffi.Pointer<ffi.Void> refCon;
}

final class opaqueCMSampleBuffer extends ffi.Opaque {}

typedef CMSampleBufferRef = ffi.Pointer<opaqueCMSampleBuffer>;

final class CMSampleTimingInfo extends ffi.Struct {
  external CMTime duration;

  external CMTime presentationTimeStamp;

  external CMTime decodeTimeStamp;
}

final class OpaqueVTCompressionSession extends ffi.Opaque {}

typedef VTCompressionSessionRef = ffi.Pointer<OpaqueVTCompressionSession>;
typedef VTCompressionOutputCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> outputCallbackRefCon,
          ffi.Pointer<ffi.Void> sourceFrameRefCon,
          OSStatus status,
          ffi.UnsignedInt infoFlags,
          CMSampleBufferRef sampleBuffer,
        )
      >
    >;

final class OpaqueVTDecompressionSession extends ffi.Opaque {}

typedef VTDecompressionSessionRef = ffi.Pointer<OpaqueVTDecompressionSession>;
typedef VTDecompressionOutputCallback =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> decompressionOutputRefCon,
          ffi.Pointer<ffi.Void> sourceFrameRefCon,
          OSStatus status,
          ffi.UnsignedInt infoFlags,
          CVImageBufferRef imageBuffer,
          CMTime presentationTimeStamp,
          CMTime presentationDuration,
        )
      >
    >;

@ffi.Packed(4)
final class VTDecompressionOutputCallbackRecord extends ffi.Struct {
  external VTDecompressionOutputCallback decompressionOutputCallback;

  external ffi.Pointer<ffi.Void> decompressionOutputRefCon;
}

const int kCVPixelFormatType_420YpCbCr8Planar = 2033463856;

const int kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange = 875704438;

const int kCVPixelFormatType_420YpCbCr8BiPlanarFullRange = 875704422;

const int kCMVideoCodecType_H264 = 1635148593;

const int __COREFOUNDATION_COREFOUNDATION__ = 1;

const int __COREFOUNDATION__ = 1;

const int __COREFOUNDATION_CFBASE__ = 1;

const int __COREFOUNDATION_CFAVAILABILITY__ = 1;

const int __CF_ENUM_FIXED_IS_AVAILABLE = 1;

const int CF_HAS_TYPED_ALLOCATOR = 0;

const int TRUE = 1;

const int FALSE = 0;

const double kCFCoreFoundationVersionNumber10_0 = 196.4;

const double kCFCoreFoundationVersionNumber10_0_3 = 196.5;

const double kCFCoreFoundationVersionNumber10_1 = 226.0;

const double kCFCoreFoundationVersionNumber10_1_1 = 226.0;

const double kCFCoreFoundationVersionNumber10_1_2 = 227.2;

const double kCFCoreFoundationVersionNumber10_1_3 = 227.2;

const double kCFCoreFoundationVersionNumber10_1_4 = 227.3;

const double kCFCoreFoundationVersionNumber10_2 = 263.0;

const double kCFCoreFoundationVersionNumber10_2_1 = 263.1;

const double kCFCoreFoundationVersionNumber10_2_2 = 263.1;

const double kCFCoreFoundationVersionNumber10_2_3 = 263.3;

const double kCFCoreFoundationVersionNumber10_2_4 = 263.3;

const double kCFCoreFoundationVersionNumber10_2_5 = 263.5;

const double kCFCoreFoundationVersionNumber10_2_6 = 263.5;

const double kCFCoreFoundationVersionNumber10_2_7 = 263.5;

const double kCFCoreFoundationVersionNumber10_2_8 = 263.5;

const double kCFCoreFoundationVersionNumber10_3 = 299.0;

const double kCFCoreFoundationVersionNumber10_3_1 = 299.0;

const double kCFCoreFoundationVersionNumber10_3_2 = 299.0;

const double kCFCoreFoundationVersionNumber10_3_3 = 299.3;

const double kCFCoreFoundationVersionNumber10_3_4 = 299.31;

const double kCFCoreFoundationVersionNumber10_3_5 = 299.31;

const double kCFCoreFoundationVersionNumber10_3_6 = 299.32;

const double kCFCoreFoundationVersionNumber10_3_7 = 299.33;

const double kCFCoreFoundationVersionNumber10_3_8 = 299.33;

const double kCFCoreFoundationVersionNumber10_3_9 = 299.35;

const double kCFCoreFoundationVersionNumber10_4 = 368.0;

const double kCFCoreFoundationVersionNumber10_4_1 = 368.1;

const double kCFCoreFoundationVersionNumber10_4_2 = 368.11;

const double kCFCoreFoundationVersionNumber10_4_3 = 368.18;

const double kCFCoreFoundationVersionNumber10_4_4_Intel = 368.26;

const double kCFCoreFoundationVersionNumber10_4_4_PowerPC = 368.25;

const double kCFCoreFoundationVersionNumber10_4_5_Intel = 368.26;

const double kCFCoreFoundationVersionNumber10_4_5_PowerPC = 368.25;

const double kCFCoreFoundationVersionNumber10_4_6_Intel = 368.26;

const double kCFCoreFoundationVersionNumber10_4_6_PowerPC = 368.25;

const double kCFCoreFoundationVersionNumber10_4_7 = 368.27;

const double kCFCoreFoundationVersionNumber10_4_8 = 368.27;

const double kCFCoreFoundationVersionNumber10_4_9 = 368.28;

const double kCFCoreFoundationVersionNumber10_4_10 = 368.28;

const double kCFCoreFoundationVersionNumber10_4_11 = 368.31;

const double kCFCoreFoundationVersionNumber10_5 = 476.0;

const double kCFCoreFoundationVersionNumber10_5_1 = 476.0;

const double kCFCoreFoundationVersionNumber10_5_2 = 476.1;

const double kCFCoreFoundationVersionNumber10_5_3 = 476.13;

const double kCFCoreFoundationVersionNumber10_5_4 = 476.14;

const double kCFCoreFoundationVersionNumber10_5_5 = 476.15;

const double kCFCoreFoundationVersionNumber10_5_6 = 476.17;

const double kCFCoreFoundationVersionNumber10_5_7 = 476.18;

const double kCFCoreFoundationVersionNumber10_5_8 = 476.19;

const double kCFCoreFoundationVersionNumber10_6 = 550.0;

const double kCFCoreFoundationVersionNumber10_6_1 = 550.0;

const double kCFCoreFoundationVersionNumber10_6_2 = 550.13;

const double kCFCoreFoundationVersionNumber10_6_3 = 550.19;

const double kCFCoreFoundationVersionNumber10_6_4 = 550.29;

const double kCFCoreFoundationVersionNumber10_6_5 = 550.42;

const double kCFCoreFoundationVersionNumber10_6_6 = 550.42;

const double kCFCoreFoundationVersionNumber10_6_7 = 550.42;

const double kCFCoreFoundationVersionNumber10_6_8 = 550.43;

const double kCFCoreFoundationVersionNumber10_7 = 635.0;

const double kCFCoreFoundationVersionNumber10_7_1 = 635.0;

const double kCFCoreFoundationVersionNumber10_7_2 = 635.15;

const double kCFCoreFoundationVersionNumber10_7_3 = 635.19;

const double kCFCoreFoundationVersionNumber10_7_4 = 635.21;

const double kCFCoreFoundationVersionNumber10_7_5 = 635.21;

const double kCFCoreFoundationVersionNumber10_8 = 744.0;

const double kCFCoreFoundationVersionNumber10_8_1 = 744.0;

const double kCFCoreFoundationVersionNumber10_8_2 = 744.12;

const double kCFCoreFoundationVersionNumber10_8_3 = 744.18;

const double kCFCoreFoundationVersionNumber10_8_4 = 744.19;

const double kCFCoreFoundationVersionNumber10_9 = 855.11;

const double kCFCoreFoundationVersionNumber10_9_1 = 855.11;

const double kCFCoreFoundationVersionNumber10_9_2 = 855.14;

const double kCFCoreFoundationVersionNumber10_10 = 1151.16;

const double kCFCoreFoundationVersionNumber10_10_1 = 1151.16;

const int kCFCoreFoundationVersionNumber10_10_2 = 1152;

const double kCFCoreFoundationVersionNumber10_10_3 = 1153.18;

const double kCFCoreFoundationVersionNumber10_10_4 = 1153.18;

const double kCFCoreFoundationVersionNumber10_10_5 = 1153.18;

const int kCFCoreFoundationVersionNumber10_10_Max = 1199;

const int kCFCoreFoundationVersionNumber10_11 = 1253;

const double kCFCoreFoundationVersionNumber10_11_1 = 1255.1;

const double kCFCoreFoundationVersionNumber10_11_2 = 1256.14;

const double kCFCoreFoundationVersionNumber10_11_3 = 1256.14;

const double kCFCoreFoundationVersionNumber10_11_4 = 1258.1;

const int kCFCoreFoundationVersionNumber10_11_Max = 1299;

const int ISA_PTRAUTH_DISCRIMINATOR = 27361;

const int __COREFOUNDATION_CFARRAY__ = 1;

const int __COREFOUNDATION_CFBAG__ = 1;

const int __COREFOUNDATION_CFBINARYHEAP__ = 1;

const int __COREFOUNDATION_CFBITVECTOR__ = 1;

const int __COREFOUNDATION_CFBYTEORDER__ = 1;

const int CF_USE_OSBYTEORDER_H = 1;

const int __COREFOUNDATION_CFCALENDAR__ = 1;

const int __COREFOUNDATION_CFLOCALE__ = 1;

const int __COREFOUNDATION_CFDICTIONARY__ = 1;

const int __COREFOUNDATION_CFNOTIFICATIONCENTER__ = 1;

const int __COREFOUNDATION_CFDATE__ = 1;

const int __COREFOUNDATION_CFTIMEZONE__ = 1;

const int __COREFOUNDATION_CFDATA__ = 1;

const int __COREFOUNDATION_CFSTRING__ = 1;

const int __COREFOUNDATION_CFCHARACTERSET__ = 1;

const int __COREFOUNDATION_CFERROR__ = 1;

const int kCFStringEncodingInvalidId = 4294967295;

const int __kCFStringInlineBufferLength = 64;

const int __COREFOUNDATION_CFCGTYPES__ = 1;

const int CGFLOAT_IS_DOUBLE = 1;

const double CGFLOAT_MIN = 2.2250738585072014e-308;

const double CGFLOAT_MAX = 1.7976931348623157e+308;

const double CGFLOAT_EPSILON = 2.220446049250313e-16;

const int CGFLOAT_DEFINED = 1;

const int CGVECTOR_DEFINED = 1;

const int __COREFOUNDATION_CFDATEFORMATTER__ = 1;

const int __COREFOUNDATION_CFNUMBER__ = 1;

const int __COREFOUNDATION_CFNUMBERFORMATTER__ = 1;

const int __COREFOUNDATION_CFPREFERENCES__ = 1;

const int __COREFOUNDATION_CFPROPERTYLIST__ = 1;

const int __COREFOUNDATION_CFSTREAM__ = 1;

const int __COREFOUNDATION_CFURL__ = 1;

const int __COREFOUNDATION_CFRUNLOOP__ = 1;

const int __COREFOUNDATION_CFSOCKET__ = 1;

const int __COREFOUNDATION_CFSET__ = 1;

const int __COREFOUNDATION_CFSTRINGENCODINGEXT__ = 1;

const int __COREFOUNDATION_CFTREE__ = 1;

const int __COREFOUNDATION_CFURLACCESS__ = 1;

const int __COREFOUNDATION_CFUUID__ = 1;

const int __COREFOUNDATION_CFUTILITIES__ = 1;

const int __COREFOUNDATION_CFBUNDLE__ = 1;

const int __COREFOUNDATION_CFMESSAGEPORT__ = 1;

const int __COREFOUNDATION_CFPLUGIN__ = 1;

const int COREFOUNDATION_CFPLUGINCOM_SEPARATE = 1;

const int __COREFOUNDATION_CFMACHPORT__ = 1;

const int __COREFOUNDATION_CFATTRIBUTEDSTRING__ = 1;

const int __COREFOUNDATION_CFURLENUMERATOR__ = 1;

const int __COREFOUNDATION_CFFILESECURITY__ = 1;

const int __COREFOUNDATION_CFSTRINGTOKENIZER__ = 1;

const int __COREFOUNDATION_CFFILEDESCRIPTOR__ = 1;

const int __COREFOUNDATION_CFUSERNOTIFICATION__ = 1;

const int __COREFOUNDATION_CFXMLNODE__ = 1;

const int __COREFOUNDATION_CFXMLPARSER__ = 1;

const int __COREVIDEO_CVRETURN_H__ = 1;

const int __COREVIDEO_CVBASE_H__ = 1;

const int COREVIDEO_TRUE = 1;

const int COREVIDEO_FALSE = 0;

const int COREVIDEO_SUPPORTS_DIRECT3D = 0;

const int COREVIDEO_SUPPORTS_OPENGL = 1;

const int COREVIDEO_SUPPORTS_OPENGLES = 0;

const int COREVIDEO_SUPPORTS_COLORSPACE = 1;

const int COREVIDEO_SUPPORTS_DISPLAYLINK = 1;

const int COREVIDEO_SUPPORTS_IOSURFACE = 1;

const int COREVIDEO_SUPPORTS_PREFETCH = 1;

const int COREVIDEO_SUPPORTS_IOSURFACE_PREFETCH = 1;

const int COREVIDEO_SUPPORTS_GLES_TEX_IMAGE_IOSURFACE = 1;

const int COREVIDEO_USE_IOSURFACEREF = 0;

const int COREVIDEO_SUPPORTS_METAL = 1;

const int COREVIDEO_SUPPORTS_PERMANENT_ALLOCATOR = 0;

const int COREVIDEO_USE_DERIVED_ENUMS_FOR_CONSTANTS = 1;

const int COREVIDEO_DECLARE_NULLABILITY = 1;

const int __COREVIDEO_CVHOSTTIME_H__ = 1;

const int __COREVIDEO_CVDISPLAYLINK_H__ = 1;

const int __COREVIDEO_CVBUFFER_H__ = 1;

const int __COREVIDEO_CVPIXELBUFFER_H__ = 1;

const int __COREVIDEO_CVIMAGEBUFFER_H__ = 1;

const int __COREVIDEO_CVPIXELBUFFERIOSURFACE_H__ = 1;

const int COREVIDEO_INCLUDED_IOSURFACE_HEADER_FILE = 1;

const int __COREVIDEO__CVPIXELBUFFERPOOL_H__ = 1;

const int __COREVIDEO_CVOPENGLBUFFER_H__ = 1;

const int __COREVIDEO__CVOPENGLBUFFERPOOL_H__ = 1;

const int __COREVIDEO_CVOPENGLTEXTURE_H__ = 1;

const int __COREVIDEO__CVOPENGLTEXTURECACHE_H__ = 1;

const int __COREVIDEO_CVMETALTEXTURE_H__ = 1;

const int __COREVIDEO__CVMETALTEXTURECACHE_H__ = 1;

const int __COREVIDEO_CVMETALBUFFER_H__ = 1;

const int __COREVIDEO__CVMETALBUFFERCACHE_H__ = 1;

const int COREMEDIA_TRUE = 1;

const int COREMEDIA_FALSE = 0;

const int COREMEDIA_EXPORTS_USE_EXPLICIT_VISIBILITY = 0;

const int CMITEMCOUNT_MAX = 9223372036854775807;

const int COREMEDIA_USE_ALIGNED_CMBASECLASS_VERSION = 1;

const int COREMEDIA_CMBASECLASS_VERSION_IS_POINTER_ALIGNED = 1;

const int COREMEDIA_USE_DERIVED_ENUMS_FOR_CONSTANTS = 1;

const int COREMEDIA_DECLARE_NULLABILITY = 1;

const int COREMEDIA_DECLARE_NULLABILITY_BEGIN_END = 1;

const int COREMEDIA_DECLARE_BRIDGED_TYPES = 1;

const int COREMEDIA_DECLARE_RETURNS_RETAINED = 1;

const int COREMEDIA_DECLARE_RETURNS_RETAINED_ON_PARAMETERS = 1;

const int COREMEDIA_DECLARE_RETURNS_NOT_RETAINED_ON_PARAMETERS = 1;

const int COREMEDIA_DECLARE_RETURNS_RETAINED_BLOCK = 1;

const int COREMEDIA_DECLARE_RELEASES_ARGUMENT = 1;

const int kCMTimeMaxTimescale = 2147483647;

const int CMTIMEBASE_USE_SOURCE_TERMINOLOGY = 1;

const double kCMTimebaseVeryLongCFTimeInterval = 8073216000.0;

const double kCMTimebaseFarFutureCFAbsoluteTime = 8073216000.0;

const int VT_SUPPORT_COLORSYNC_PIXEL_TRANSFER = 1;
